#!/usr/bin/env python3
"""
Prebuild script for nakake/gpui-bindings (issue #93, G2).

Registered in moon.mod via `options("--moonbit-unstable-prebuild": "build.py")`.
Runs when this module is consumed as a path/git dependency, or when the module
itself is built with `moon build` / `moon test`.

What it does:
  1. Resolves the consumption route (RFC 0005 D3):
       checkout         — sibling ../gpui-sys exists (path/git dependency or
                          repo checkout). Builds the sibling directly.
       wrapper-registry — no sibling (module expanded under .mooncakes/).
                          Generates a staticlib wrapper crate in the user
                          cache that depends on gpui-sys from crates.io
                          (pinned by GPUI_SYS_VERSION below) and builds that.
       wrapper-path     — wrapper crate with a path dependency instead
                          (pre-publish CI simulation; the dependency form
                          does not affect codegen or linking).
     GPUI_BINDINGS_ROUTE forces a route for verification;
     GPUI_BINDINGS_GPUI_SYS_PATH points wrapper-path at a gpui-sys copy.
  2. checkout route only: computes the MoonBit callback symbol
     (dispatch_entry) deterministically and writes gpui-sys/mb_symbol.txt if
     absent. Wrapper routes skip this: the packaged gpui-sys build.rs
     computes the same value from its own abi.toml.
  3. Runs `cargo build` to produce the staticlib.
  4. Runs `cargo rustc -- --print native-static-libs` to capture link flags.
  5. Normalizes the flags per-OS (mirrors build.sh logic).
  6. Outputs a LinkConfig JSON to stdout (the ONLY stdout output).

All diagnostic output goes to stderr. stdout is reserved for the JSON output —
moon parses the entire stdout as JSON (serde_json::from_slice).

Protocol reference (moon 0.1.20260721, crates/moonutil/src/build_script.rs):
  stdin:  {"env": {...}, "paths": {"module_root": "...", "out_dir": "TODO"}}
  stdout: {"link_configs": [{"package": "...", "link_flags": "...", ...}]}
  stderr: inherited (free-form diagnostics)

Limitations:
  - Linux x86_64: verified.
  - macOS arm64/x86_64: best-effort, unverified (no test environment).
  - Windows MSVC x64: MSVC-style flags (/LIBPATH:, gpui_sys.lib)
    implemented; being verified on windows-latest CI.
  - `rerun_if` does not work in current moon; cargo build runs on every
    `moon build` invocation (incremental, so warm builds are fast).
"""

import glob
import json
import os
import platform
import re
import subprocess
import sys
import tempfile

# crates.io pin for the wrapper routes (RFC 0005 D1). Caret semantics: cargo
# reads "0.1.0" as >=0.1.0 <0.2.0, so gpui-sys patch releases (which must not
# break the ABI/symbol contract, see docs/versioning.md) reach consumers whose
# module copy carries this build.py, while a 0.2 bump requires a module update
# (lockstep versioning). build.sh preflight asserts gpui-sys/Cargo.toml stays
# inside this range.
GPUI_SYS_VERSION = "0.1.0"

WRAPPER_LIB_RS = """\
// Generated by nakake/gpui-bindings build.py. Do not edit; the file is
// rewritten whenever its expected content changes.
extern crate gpui_sys;
"""


def log(msg):
    """Diagnostic output to stderr (stdout is reserved for JSON)."""
    sys.stderr.write(f"[gpui-bindings prebuild] {msg}\n")
    sys.stderr.flush()


def escape_mangling_component(s):
    """Escape a path component for MoonBit symbol mangling.

    Rules (verified 2026-08-01, moon 0.1.20260721):
      '_' -> '__'  (first)
      '-' -> '_2d' (second)
    """
    return s.replace("_", "__").replace("-", "_2d")


def compute_callback_symbol(abi_toml):
    """Compute the mangled symbol for nakake/gpui-bindings :: dispatch_entry.

    The callback lives in the module's root package (nakake/gpui-bindings),
    so no package component is mangled into the symbol; only the module parts
    and the function name appear. Both the function name and the module come
    from gpui-sys/abi.toml's `[callback]`, the single source of truth (RFC 0004);
    `gpui-sys/build.rs` computes the same value from the same two fields.

    Mangling scheme: _M0FP<N><len1><comp1><len2><comp2>...<fnlen><fn>
    where N = number of path components (module parts only).

    For module nakake/gpui-bindings, function dispatch_entry:
      components: ["nakake", "gpui-bindings"]
      escaped:    ["nakake", "gpui_2dbindings"]
      fn:         "dispatch_entry" -> "dispatch__entry" (15 chars)
      -> _M0FP2 6nakake 15gpui_2dbindings 15dispatch__entry
      -> _M0FP26nakake15gpui_2dbindings15dispatch__entry

    The leading '_' is the ELF symbol prefix. Mach-O adds one more via the
    linker (#[link_name] uses one underscore; the linker adds the other).
    """
    function = read_callback_name(abi_toml)

    module_parts = read_callback_module(abi_toml).split("/")
    components = [escape_mangling_component(p) for p in module_parts]
    fn = escape_mangling_component(function)

    parts = [str(len(components))]  # N
    for comp in components:
        parts.append(str(len(comp)))
        parts.append(comp)
    parts.append(str(len(fn)))
    parts.append(fn)

    return "_M0FP" + "".join(parts)


def read_callback_field(abi_toml, key, pattern):
    """Extract a string field from `[callback]` in gpui-sys/abi.toml.

    `pattern` validates the value; a value that does not match is an error
    rather than something to mangle blindly. Exits on error.
    """
    with open(abi_toml) as f:
        lines = f.read().splitlines()
    in_callback = False
    for raw in lines:
        line = re.sub(r"\s*#.*", "", raw).strip()
        if not line:
            continue
        if re.match(r"^\[[A-Za-z_][A-Za-z0-9_]*\]$", line):
            in_callback = line == "[callback]"
            continue
        if not in_callback:
            continue
        m = re.match(rf"^{key}\s*=\s*\"([^\"]*)\"\s*$", line)
        if m:
            value = m.group(1)
            if not re.match(pattern, value):
                log(f"ERROR: invalid [callback] {key} in abi.toml: {value}")
                sys.exit(1)
            return value
    log(f"ERROR: could not derive [callback] {key} from {abi_toml}")
    sys.exit(1)


def read_callback_name(abi_toml):
    """Extract `[callback] name` from gpui-sys/abi.toml. Exits on error."""
    return read_callback_field(abi_toml, "name", r"^[A-Za-z_][A-Za-z0-9_]*$")


def read_callback_module(abi_toml):
    """Extract `[callback] module` from gpui-sys/abi.toml. Exits on error.

    The owning MoonBit module (`nakake/gpui-bindings`). Declared in abi.toml so
    this script and `gpui-sys/build.rs` derive the mangled symbol from one
    place instead of each hardcoding the module path.
    """
    return read_callback_field(
        abi_toml, "module", r"^[A-Za-z0-9_-]+(/[A-Za-z0-9_-]+)*$"
    )


def normalize_native_libs(native_libs_str, os_pkg):
    """Normalize cargo's native-static-libs output per-OS.

    Mirrors build.sh's normalize_native_libs + belt-and-suspenders logic:
      - Drop -lc (all platforms): cc driver links it implicitly.
      - macOS: drop -lm (math lives in libSystem).
      - Linux: rewrite XCB/XKB to versioned SONAME form (-l:libfoo.so.N).
      - Linux: ensure -l:libxcb-xkb.so.1 is present.
      - Windows: drop /defaultlib:(libcmt|msvcrt) (moon links /MT always).
    """
    tokens = native_libs_str.split()
    normalized = []

    for lib in tokens:
        if lib == "-lc":
            continue
        if os_pkg == "windows" and re.match(
            r"^/defaultlib:(libcmt|msvcrt)$", lib, re.IGNORECASE
        ):
            continue
        if os_pkg == "macos" and lib == "-lm":
            continue
        if os_pkg == "linux":
            replacements = {
                "-lxcb": "-l:libxcb.so.1",
                "-lxcb-xkb": "-l:libxcb-xkb.so.1",
                "-lxkbcommon": "-l:libxkbcommon.so.0",
                "-lxkbcommon-x11": "-l:libxkbcommon-x11.so.0",
            }
            if lib in replacements:
                lib = replacements[lib]
            if lib == "-l:libxcb-xkb.so.1" and lib in normalized:
                continue
        normalized.append(lib)

    if os_pkg == "linux" and "-l:libxcb-xkb.so.1" not in normalized:
        normalized.append("-l:libxcb-xkb.so.1")

    return normalized


def user_cache_dir(os_pkg):
    """OS-conventional per-user cache root, or None if unresolvable."""
    if os_pkg == "windows":
        base = os.environ.get("LOCALAPPDATA")
        if not base:
            home = os.path.expanduser("~")
            base = os.path.join(home, "AppData", "Local") if home != "~" else None
        return base
    home = os.path.expanduser("~")
    if home == "~" or not home:
        return None
    if os_pkg == "macos":
        return os.path.join(home, "Library", "Caches")
    return os.environ.get("XDG_CACHE_HOME") or os.path.join(home, ".cache")


def write_if_different(path, content):
    """Write `path` atomically iff its content differs from `content`.

    Always content-compares (never "write only if missing"): a route switch
    must rewrite the wrapper's dependency line, or a later e2e run would
    silently test the previous route. The temp-file + rename keeps a
    concurrent build from ever observing a half-written manifest.
    """
    try:
        with open(path) as f:
            if f.read() == content:
                return False
    except OSError:
        pass
    fd, tmp = tempfile.mkstemp(dir=os.path.dirname(path), prefix=".tmp-")
    try:
        with os.fdopen(fd, "w") as f:
            f.write(content)
        os.replace(tmp, path)
    except BaseException:
        try:
            os.remove(tmp)
        except OSError:
            pass
        raise
    log(f"wrote {path}")
    return True


def setup_wrapper(route, module_root, os_pkg, sibling):
    """Create/refresh the wrapper crate in the user cache; return its dir.

    Also routes cargo output into the shared cache target dir unless the
    caller already set CARGO_TARGET_DIR (cargo convention; CI's cache hook).
    """
    cache_base = user_cache_dir(os_pkg)
    if not cache_base:
        cache_base = os.path.join(module_root, ".gpui-wrapper-cache")
        log(f"WARNING: could not resolve a user cache directory; falling back to {cache_base}")
    app_dir = os.path.join(cache_base, "nakake-gpui-bindings")
    wrapper_dir = os.path.join(app_dir, "wrapper", GPUI_SYS_VERSION)
    os.makedirs(os.path.join(wrapper_dir, "src"), exist_ok=True)

    if route == "wrapper-registry":
        dep_line = f'gpui-sys = "{GPUI_SYS_VERSION}"'
    else:
        dep_path = os.environ.get("GPUI_BINDINGS_GPUI_SYS_PATH") or sibling
        if not os.path.isdir(dep_path):
            log(f"ERROR: wrapper-path route needs a gpui-sys directory at {dep_path}")
            log("Set GPUI_BINDINGS_GPUI_SYS_PATH or provide a sibling gpui-sys/.")
            sys.exit(1)
        # TOML literal string + forward slashes: no escaping trouble on Windows.
        dep_line = "gpui-sys = { path = '%s' }" % os.path.abspath(dep_path).replace("\\", "/")

    cargo_toml = f"""\
# Generated by nakake/gpui-bindings build.py. Do not edit; the file is
# rewritten whenever its expected content changes (route/pin switches).
# The empty [workspace] keeps any enclosing workspace from capturing this
# crate; publish = false keeps it out of cargo publish by construction.
[workspace]

[package]
name = "gpui_sys_wrapper"
version = "0.0.0"
edition = "2021"
publish = false

[lib]
crate-type = ["staticlib"]
path = "src/lib.rs"

[dependencies]
{dep_line}
"""
    write_if_different(os.path.join(wrapper_dir, "Cargo.toml"), cargo_toml)
    write_if_different(os.path.join(wrapper_dir, "src", "lib.rs"), WRAPPER_LIB_RS)

    if "CARGO_TARGET_DIR" not in os.environ:
        os.environ["CARGO_TARGET_DIR"] = os.path.join(app_dir, "target")
    log(f"wrapper dir: {wrapper_dir}")
    log(f"cargo target dir: {os.environ.get('CARGO_TARGET_DIR', '(wrapper-local default)')}")
    return wrapper_dir


def run(cmd, **kwargs):
    """Run a command, logging it. Raises on failure."""
    log(f"  $ {' '.join(cmd)}")
    return subprocess.run(cmd, **kwargs)


def msvc_path(path):
    """Format a Windows path for a link flag.

    moon parses link_flags with shlex, which eats backslashes as escapes
    (observed in PR #102 CI logs). link.exe accepts forward-slash paths, so
    normalize to '/'. Wrap in double quotes when the path contains whitespace
    so shlex does not split it.
    """
    p = os.path.abspath(path).replace("\\", "/")
    if any(c.isspace() for c in p):
        return '"' + p + '"'
    return p


def cargo_build(build_dir, rust_target, rust_lib_dir=None, lib_base="gpui_sys"):
    """Build the staticlib crate in `build_dir`. Logs and exits on failure."""
    log(f"building staticlib crate in {build_dir}...")
    result = run(
        ["cargo", "build", "--target", rust_target],
        cwd=build_dir,
        capture_output=True,
        text=True,
    )
    if result.returncode != 0:
        log("ERROR: cargo build failed:")
        sys.stderr.write(result.stderr)
        sys.exit(1)
    # The crate is staticlib-only; a stale dynamic lib left by a past
    # crate-type experiment would win over the .a on the -l link line with
    # no build-time error. Drop any such leftover.
    if rust_lib_dir:
        for ext in ("dylib", "so"):
            path = os.path.join(rust_lib_dir, f"lib{lib_base}.{ext}")
            if os.path.exists(path):
                os.remove(path)
                log(f"removed stale {path}")


def extract_native_libs(build_dir, rust_target):
    """Capture cargo's native-static-libs list. Logs and exits on failure."""
    log("extracting native-static-libs...")
    result = run(
        [
            "cargo", "rustc", "--target", rust_target,
            "--lib", "--crate-type", "staticlib",
            "--", "--print", "native-static-libs",
        ],
        cwd=build_dir,
        capture_output=True,
        text=True,
    )
    if result.returncode != 0:
        log("ERROR: cargo rustc --print native-static-libs failed:")
        sys.stderr.write(result.stderr)
        sys.exit(1)

    # rustc prints native-static-libs to stderr
    native_libs_line = ""
    for line in result.stderr.splitlines():
        line = re.sub(r"\x1b\[[0-9;]*m", "", line)  # strip ANSI
        if "native-static-libs:" in line:
            native_libs_line = line.split("native-static-libs:", 1)[1].strip()
            break
    if not native_libs_line:
        log("ERROR: could not find native-static-libs in cargo output")
        sys.exit(1)
    log(f"raw native libs: {native_libs_line}")
    return native_libs_line


def main():
    # --- Read BuildScriptEnvironment from stdin ---
    env_input = json.load(sys.stdin)
    module_root = env_input["paths"]["module_root"]
    log(f"module_root={module_root}")

    # --- Determine OS ---
    system = platform.system()
    if system == "Linux":
        os_pkg = "linux"
    elif system == "Darwin":
        os_pkg = "macos"
    elif system == "Windows":
        os_pkg = "windows"
    else:
        log(f"ERROR: unsupported OS: {system}")
        sys.exit(1)
    log(f"os={os_pkg} arch={platform.machine()}")

    # --- Resolve the consumption route (RFC 0005 D3) ---
    # The real consumption forms are binary: a .mooncakes/ expansion
    # structurally has no sibling gpui-sys, while checkout/path/git forms
    # always do. GPUI_BINDINGS_ROUTE overrides for verification only.
    sibling = os.path.normpath(os.path.join(module_root, "..", "gpui-sys"))
    route = (os.environ.get("GPUI_BINDINGS_ROUTE") or "auto").strip() or "auto"
    if route == "auto":
        route = "checkout" if os.path.isdir(sibling) else "wrapper-registry"
    elif route not in ("checkout", "wrapper-path", "wrapper-registry"):
        log(f"ERROR: unknown GPUI_BINDINGS_ROUTE: {route}")
        log("Valid values: auto, checkout, wrapper-path, wrapper-registry.")
        sys.exit(1)
    log(f"route: {route}")

    if route == "checkout":
        if not os.path.isdir(sibling):
            log(f"ERROR: gpui-sys not found at {sibling}")
            log("The checkout route needs gpui-sys/ as a sibling of the module")
            log("root (path dependency or git clone). Registry consumers use")
            log("the wrapper-registry route automatically.")
            sys.exit(1)
        build_dir = sibling
        lib_base = "gpui_sys"

        # --- Compute and write the callback symbol ---
        # Wrapper routes skip this: the packaged gpui-sys build.rs computes
        # the same value from its own abi.toml (and mb_symbol.txt is not part
        # of the published crate).
        symbol = compute_callback_symbol(os.path.join(sibling, "abi.toml"))
        log(f"callback symbol: {symbol}")

        mb_symbol_path = os.path.join(sibling, "mb_symbol.txt")
        if os.path.exists(mb_symbol_path):
            with open(mb_symbol_path) as f:
                existing = f.read().strip()
            if existing and existing != symbol:
                log(f"WARNING: mb_symbol.txt='{existing}' != computed='{symbol}'")
                log("The mangling scheme may have changed. Verify and update")
                log("compute_callback_symbol() in build.py.")
        else:
            with open(mb_symbol_path, "w") as f:
                f.write(symbol + "\n")
            log(f"wrote {mb_symbol_path}")
    else:
        build_dir = setup_wrapper(route, module_root, os_pkg, sibling)
        lib_base = "gpui_sys_wrapper"

    # --- Determine Rust host target ---
    result = run(["rustc", "-vV"], capture_output=True, text=True, check=True)
    rust_target = None
    for line in result.stdout.splitlines():
        if line.startswith("host:"):
            rust_target = line.split(":", 1)[1].strip()
            break
    if not rust_target:
        log("ERROR: could not determine Rust host target from `rustc -vV`")
        sys.exit(1)
    log(f"rust target: {rust_target}")

    # --- Force the static CRT on Windows ---
    if os_pkg == "windows":
        # moon's native backend always compiles and links with /MT (it appends
        # /MT after user flags, so /MD can never win); build the Rust static
        # lib with the same static CRT to avoid a CRT mismatch at link time.
        flag = "-C target-feature=+crt-static"
        existing = os.environ.get("RUSTFLAGS", "")
        if "target-feature=+crt-static" not in existing:
            os.environ["RUSTFLAGS"] = (existing + " " + flag).strip() if existing else flag
        log(f"RUSTFLAGS={os.environ['RUSTFLAGS']}")

    # --- Determine the Rust library directory ---
    result = run(
        ["cargo", "metadata", "--no-deps", "--format-version", "1"],
        cwd=build_dir,
        capture_output=True,
        text=True,
        check=True,
    )
    metadata = json.loads(result.stdout)
    target_dir = metadata["target_directory"]
    rust_lib_dir = os.path.join(target_dir, rust_target, "debug")
    log(f"rust lib dir: {rust_lib_dir}")

    # --- Build gpui-sys / extract native-static-libs ---
    # On Windows the print step runs FIRST: `cargo rustc -- --print` may
    # invalidate a previously built .lib (cargo cleans stale artifacts and
    # rustc exits after printing without producing output), so running
    # `cargo build` last guarantees gpui_sys.lib exists for moon's link step.
    if os_pkg == "windows":
        native_libs_line = extract_native_libs(build_dir, rust_target)
        cargo_build(build_dir, rust_target, rust_lib_dir, lib_base)
        staticlib_path = os.path.join(rust_lib_dir, f"{lib_base}.lib")
        if not os.path.exists(staticlib_path):
            log(f"ERROR: {staticlib_path} not found after cargo build")
            sys.exit(1)
    else:
        cargo_build(build_dir, rust_target, rust_lib_dir, lib_base)
        native_libs_line = extract_native_libs(build_dir, rust_target)

    # --- Normalize per-OS ---
    normalized = normalize_native_libs(native_libs_line, os_pkg)

    # --- Assemble link flags (order matters: search paths before libs) ---
    if os_pkg == "windows":
        # gpui's build.rs emits an extra static lib (gpui.lib) under
        # target/<host>/debug/build on Windows; add every dir holding a .lib.
        extra_dirs = []
        build_tree = os.path.join(rust_lib_dir, "build")
        if os.path.isdir(build_tree):
            for root, _dirs, files in os.walk(build_tree):
                if any(name.endswith(".lib") for name in files):
                    extra_dirs.append(root)

        # windows-rs ships its import libs inside the cargo registry checkout;
        # the linker needs those dirs on the search path too.
        win_lib_dirs = []
        user_profile = os.environ.get("USERPROFILE")
        if user_profile:
            registry_src = os.path.join(user_profile, ".cargo", "registry", "src")
            for d in sorted(glob.glob(
                os.path.join(registry_src, "*", "windows_x86_64_msvc-*", "lib")
            )):
                if os.path.isdir(d):
                    win_lib_dirs.append(d)

        # Dedupe preserving order.
        seen = set()
        lib_dirs = []
        for d in [rust_lib_dir] + extra_dirs + win_lib_dirs:
            if d not in seen:
                seen.add(d)
                lib_dirs.append(d)
        log(f"lib dirs: {'; '.join(lib_dirs)}")

        # moon hands link_flags to `cl`, not to `link` (verified on CI: every
        # /LIBPATH: token came back as "cl : Command line warning D9002 :
        # ignoring unknown option"). cl only forwards *file* arguments to the
        # linker, so search paths are useless here — resolve each project lib
        # to an absolute path instead. Names we cannot resolve are Windows SDK
        # libs (kernel32.lib etc.); link finds those through LIB.
        def resolve_lib(name):
            for d in lib_dirs:
                candidate = os.path.join(d, name)
                if os.path.isfile(candidate):
                    return msvc_path(candidate)
            return name

        windows_flags = []
        for token in [f"{lib_base}.lib"] + normalized:
            flag = resolve_lib(token) if token.lower().endswith(".lib") else token
            # cargo repeats the common SDK imports (advapi32/kernel32/...);
            # emitting them once keeps the command line short.
            if flag not in windows_flags:
                windows_flags.append(flag)
    else:
        search_paths = [f"-L{rust_lib_dir}"]

        # .linux-libs fallback (repo-level, gitignored)
        linux_libs = os.path.normpath(os.path.join(module_root, "..", ".linux-libs"))
        if os_pkg == "linux" and os.path.isdir(linux_libs):
            search_paths.append(f"-L{linux_libs}")
            log(f"using .linux-libs fallback: {linux_libs}")

        # System lib dir (for environments where ld doesn't inherit cc's defaults)
        if os_pkg == "linux":
            result = run(
                ["cc", "-print-file-name=libc.so"],
                capture_output=True, text=True, check=True,
            )
            libc_path = result.stdout.strip()
            if libc_path and libc_path != "libc.so":
                sys_lib_dir = os.path.dirname(os.path.abspath(libc_path))
                if os.path.isdir(sys_lib_dir):
                    search_paths.append(f"-L{sys_lib_dir}")
                    log(f"system lib dir: {sys_lib_dir}")
        elif os_pkg == "macos":
            result = run(
                ["xcrun", "--show-sdk-path"],
                capture_output=True, text=True, check=True,
            )
            sdk_lib_dir = os.path.join(result.stdout.strip(), "usr", "lib")
            if os.path.isdir(sdk_lib_dir):
                search_paths.append(f"-L{sdk_lib_dir}")
                log(f"SDK lib dir: {sdk_lib_dir}")
            # IOSurface is not always reported by cargo's native-static-libs
            normalized.extend(["-framework", "IOSurface"])

    # Final flag string: search paths -> gpui_sys -> normalized native libs
    if os_pkg == "windows":
        all_flags = windows_flags
    else:
        all_flags = search_paths + [f"-l{lib_base}"] + normalized
    link_flags = " ".join(all_flags)
    log(f"link_flags: {link_flags}")

    # --- Output LinkConfig JSON (the ONLY stdout output) ---
    output = {
        "link_configs": [
            {
                "package": "nakake/gpui-bindings/link",
                "link_flags": link_flags,
            }
        ]
    }
    print(json.dumps(output))


if __name__ == "__main__":
    main()
