use gpui::*;
use std::ffi::CStr;
use std::os::raw::c_char;
use std::sync::Mutex;

static NODES: Mutex<Vec<Option<UiNode>>> = Mutex::new(Vec::new());

// Rust -> MoonBit callback. MoonBit native does not emit a stable C export
// symbol for an executable build, so we bind directly to the compiled MoonBit
// function's mangled symbol. Rather than hard-code that (fragile) name, the
// `extern` block below is generated by build.rs from `mb_symbol.txt`, which
// `build.sh` fills by extracting the real `app.dispatch` symbol from MoonBit's
// build output — so renames / toolchain mangling changes are tracked
// automatically. The callback is invoked on click, on the main thread, while we
// are already inside the (MoonBit-initiated) GPUI event loop — safe under
// MoonBit's reference-counted runtime.
//
// Generates: `unsafe extern "C" { #[link_name = "_M0FP…3app8dispatch"] fn mb_dispatch(kind: i32, id: i32, a: i32, b: i32); }`
include!(concat!(env!("OUT_DIR"), "/mb_extern.rs"));

// Event kinds passed to MoonBit's `dispatch` — must match the EV_* constants in
// moonbit-bindings/app/app.mbt. The FFI carries a scalar payload (kind, id, a, b)
// so new event types don't grow the FFI surface — only the MoonBit `Event` enum.
const EVENT_CLICK: i32 = 1;
const EVENT_KEY: i32 = 2;

enum UiNode {
    Div {
        width: f32,
        height: f32,
        bg: Option<(u8, u8, u8)>,
        flex: bool,
        flex_col: bool,
        center: bool,
        gap: f32,
        rounded: f32,
        on_click: Option<i32>,
        children: Vec<UiNode>,
    },
    Text {
        content: String,
        color: (u8, u8, u8),
        size: f32,
    },
}

fn with_nodes<F, R>(f: F) -> R
where
    F: FnOnce(&mut Vec<Option<UiNode>>) -> R,
{
    f(&mut NODES.lock().unwrap())
}

#[unsafe(no_mangle)]
pub extern "C" fn gpui_create_div() -> i32 {
    with_nodes(|nodes| {
        let id = nodes.len() as i32;
        nodes.push(Some(UiNode::Div {
            width: 0.0,
            height: 0.0,
            bg: None,
            flex: false,
            flex_col: false,
            center: false,
            gap: 0.0,
            rounded: 0.0,
            on_click: None,
            children: Vec::new(),
        }));
        id
    })
}

/// Mark a div as clickable. `click_id` is passed back to MoonBit's `dispatch`
/// when the div is clicked.
#[unsafe(no_mangle)]
pub extern "C" fn gpui_set_on_click(handle: i32, click_id: i32) {
    with_nodes(|nodes| {
        if let Some(Some(UiNode::Div { on_click, .. })) = nodes.get_mut(handle as usize) {
            *on_click = Some(click_id);
        }
    });
}

/// Clear the whole node tree so MoonBit can rebuild it from scratch (used on
/// re-render after a click).
#[unsafe(no_mangle)]
pub extern "C" fn gpui_reset() {
    with_nodes(|nodes| nodes.clear());
}

#[unsafe(no_mangle)]
pub extern "C" fn gpui_set_size(handle: i32, w: f32, h: f32) {
    with_nodes(|nodes| {
        if let Some(Some(UiNode::Div { width, height, .. })) = nodes.get_mut(handle as usize) {
            *width = w;
            *height = h;
        }
    });
}

#[unsafe(no_mangle)]
pub extern "C" fn gpui_set_bg(handle: i32, r: u8, g: u8, b: u8) {
    with_nodes(|nodes| {
        if let Some(Some(UiNode::Div { bg, .. })) = nodes.get_mut(handle as usize) {
            *bg = Some((r, g, b));
        }
    });
}

#[unsafe(no_mangle)]
pub extern "C" fn gpui_set_flex(handle: i32, col: i32) {
    with_nodes(|nodes| {
        if let Some(Some(UiNode::Div { flex, flex_col, .. })) = nodes.get_mut(handle as usize) {
            *flex = true;
            *flex_col = col != 0;
        }
    });
}

#[unsafe(no_mangle)]
pub extern "C" fn gpui_set_center(handle: i32) {
    with_nodes(|nodes| {
        if let Some(Some(UiNode::Div { center, .. })) = nodes.get_mut(handle as usize) {
            *center = true;
        }
    });
}

#[unsafe(no_mangle)]
pub extern "C" fn gpui_set_gap(handle: i32, gap: f32) {
    with_nodes(|nodes| {
        if let Some(Some(UiNode::Div { gap: g, .. })) = nodes.get_mut(handle as usize) {
            *g = gap;
        }
    });
}

#[unsafe(no_mangle)]
pub extern "C" fn gpui_set_rounded(handle: i32, radius: f32) {
    with_nodes(|nodes| {
        if let Some(Some(UiNode::Div { rounded, .. })) = nodes.get_mut(handle as usize) {
            *rounded = radius;
        }
    });
}

#[unsafe(no_mangle)]
pub extern "C" fn gpui_create_text(text: *const c_char, r: u8, g: u8, b: u8, size: f32) -> i32 {
    let content = if text.is_null() {
        String::new()
    } else {
        unsafe { CStr::from_ptr(text) }
            .to_str()
            .unwrap_or("")
            .to_string()
    };
    with_nodes(|nodes| {
        let id = nodes.len() as i32;
        nodes.push(Some(UiNode::Text {
            content,
            color: (r, g, b),
            size,
        }));
        id
    })
}

#[unsafe(no_mangle)]
pub extern "C" fn gpui_add_child(parent: i32, child: i32) {
    with_nodes(|nodes| {
        let child_node = nodes[child as usize].take();
        if let Some(c) = child_node {
            if let Some(Some(UiNode::Div { children, .. })) = nodes.get_mut(parent as usize) {
                children.push(c);
            }
        }
    });
}

#[unsafe(no_mangle)]
pub extern "C" fn gpui_run_window(width: f32, height: f32) {
    Application::new().run(move |cx: &mut App| {
        let bounds = Bounds::centered(None, size(px(width), px(height)), cx);
        cx.open_window(
            WindowOptions {
                window_bounds: Some(WindowBounds::Windowed(bounds)),
                ..Default::default()
            },
            |window, cx| {
                cx.new(|cx| {
                    // Focus the view at construction (with `window` available), the
                    // same way GPUI's own examples do — focusing during `render`
                    // does not reliably make the element the OS first responder,
                    // so key events never arrive.
                    let focus = cx.focus_handle();
                    window.focus(&focus);
                    FfiView { focus }
                })
            },
        )
        .unwrap();
        cx.activate(true);
    });
}

struct FfiView {
    focus: FocusHandle,
}

impl Render for FfiView {
    fn render(&mut self, _window: &mut Window, cx: &mut Context<Self>) -> impl IntoElement {
        let nodes = NODES.lock().unwrap();
        let mut children = Vec::new();
        for node in nodes.iter() {
            if let Some(n) = node {
                if let Some(el) = render_node(n, cx, true) {
                    children.push(el);
                }
            }
        }
        let mut d = div()
            .size_full()
            .flex()
            .flex_col()
            .track_focus(&self.focus)
            .on_key_down(cx.listener(|_this, ev: &KeyDownEvent, _win, cx| {
                let code = key_code(ev);
                if code != 0 {
                    let mods = mods_bits(&ev.keystroke.modifiers);
                    unsafe { mb_dispatch(EVENT_KEY, 0, code, mods) };
                    cx.notify();
                }
            }));
        d.extend(children);
        d
    }
}

/// Codepoint of a single-character key (letters/digits/…); 0 for named or
/// multi-char keys (up/down/enter/…), which this demo ignores. Rust only
/// translates the platform key to a scalar; MoonBit decides what each key does.
fn key_code(ev: &KeyDownEvent) -> i32 {
    let mut chars = ev.keystroke.key.chars();
    match (chars.next(), chars.next()) {
        (Some(c), None) => c as i32,
        _ => 0,
    }
}

/// Pack modifier flags into the `b` payload slot (bit0 ctrl, 1 alt, 2 shift,
/// 3 platform/cmd, 4 fn). Unused by the demo but kept for completeness.
fn mods_bits(m: &Modifiers) -> i32 {
    (m.control as i32)
        | ((m.alt as i32) << 1)
        | ((m.shift as i32) << 2)
        | ((m.platform as i32) << 3)
        | ((m.function as i32) << 4)
}

fn render_node(
    node: &UiNode,
    cx: &mut Context<FfiView>,
    fill_available_space: bool,
) -> Option<AnyElement> {
    match node {
        UiNode::Div {
            width,
            height,
            bg,
            flex,
            flex_col,
            center,
            gap,
            rounded,
            on_click,
            children,
        } => {
            // Build children first (recursion borrows `cx`), then attach the
            // click listener (also borrows `cx`) — kept sequential to avoid an
            // aliasing borrow.
            let mut child_elements: Vec<AnyElement> = Vec::new();
            for child in children {
                if let Some(el) = render_node(child, cx, false) {
                    child_elements.push(el);
                }
            }
            let mut d = div();
            if fill_available_space {
                d = d.size_full();
            }
            if *width > 0.0 && *height > 0.0 {
                d = d.w(px(*width)).h(px(*height));
            }
            if let Some((r, g, b)) = bg {
                d = d.bg(rgb(
                    ((*r as u32) << 16) | ((*g as u32) << 8) | (*b as u32)
                ));
            }
            if *flex {
                d = d.flex();
                if *flex_col {
                    d = d.flex_col();
                }
            }
            if *center {
                d = d.justify_center().items_center();
            }
            if *gap > 0.0 {
                d = d.gap(px(*gap));
            }
            if *rounded > 0.0 {
                d = d.rounded(px(*rounded));
            }
            d.extend(child_elements);
            if let Some(cid) = *on_click {
                // A stable ElementId derived from the click id (not the volatile
                // node handle) keeps GPUI's stateful-element identity across
                // rebuilds. On click, hand the id back to MoonBit and re-render.
                let el = d
                    .id(("gpui_click", cid as usize))
                    .cursor_pointer()
                    .on_click(cx.listener(move |_this, _ev: &ClickEvent, _win, cx| {
                        unsafe { mb_dispatch(EVENT_CLICK, cid, 0, 0) };
                        cx.notify();
                    }))
                    .into_any_element();
                Some(el)
            } else {
                Some(d.into_any_element())
            }
        }
        UiNode::Text {
            content,
            color: (r, g, b),
            size,
        } => {
            // GPUI rounds element positions to whole pixels (taffy rounding),
            // so the first glyph of a line always lands at subpixel offset 0 and
            // is rasterized with a hard, un-antialiased left edge — visible as a
            // ~1px "cut" on the left of a leading round glyph such as "G".
            // Interior glyphs land at fractional offsets and get proper
            // antialiasing. Pad the string with a leading (and matching trailing)
            // space so the real first glyph becomes an interior glyph; trailing
            // whitespace is counted in the line width, so centering is preserved.
            let d = div()
                .text_color(rgb(
                    ((*r as u32) << 16) | ((*g as u32) << 8) | (*b as u32)
                ))
                .text_size(px(*size))
                .child(format!(" {content} "));
            Some(d.into_any_element())
        }
    }
}
