use gpui::*;
use std::any::Any;
use std::panic::{AssertUnwindSafe, catch_unwind};
use std::sync::Mutex;

mod abi_constants;
use abi_constants::{
    ABI_VERSION, BUFFER_VERSION, EVENT_CLICK, EVENT_KEY, EVENT_TEXT, MOD_ALT, MOD_CTRL,
    MOD_FUNCTION, MOD_PLATFORM, MOD_SHIFT, OP_ADD_CHILD, OP_DIV, OP_SET_BG, OP_SET_CENTER,
    OP_SET_FLEX, OP_SET_GAP, OP_SET_KEY, OP_SET_ON_CLICK, OP_SET_ROOT, OP_SET_ROUNDED,
    OP_SET_SIZE, OP_TEXT,
};

// Reference the version as a build-time sanity anchor until runtime FFI negotiation exists.
const _: () = assert!(ABI_VERSION > 0);

/// Committed trees, one slot per view id. `render` reads the slot for its own
/// view; a successful `gpui_build_tree` swaps a freshly built tree into it.
/// `None` = no tree committed yet (the view renders empty).
static VIEWS: Mutex<Vec<Option<UiNode>>> = Mutex::new(Vec::new());

/// Operation completed successfully.
pub const GPUI_STATUS_OK: i32 = 0;
/// A handle was negative, out of range, duplicated, or could not be allocated.
pub const GPUI_STATUS_INVALID_HANDLE: i32 = -1;
/// The handle refers to the wrong kind of node for the requested operation.
pub const GPUI_STATUS_WRONG_NODE_KIND: i32 = -2;
/// The node was already moved into another node by `gpui_add_child`.
pub const GPUI_STATUS_NODE_ABSENT: i32 = -3;
/// An internal panic was caught before it could cross the C boundary.
pub const GPUI_STATUS_INTERNAL_PANIC: i32 = -4;
/// The command buffer header magic or version did not match.
pub const GPUI_STATUS_BAD_BUFFER_VERSION: i32 = -5;
/// The command buffer ended mid-field, or carried a truncated/oversized payload.
pub const GPUI_STATUS_TRUNCATED_BUFFER: i32 = -6;
/// The command buffer named an opcode this build does not recognize.
pub const GPUI_STATUS_UNKNOWN_OPCODE: i32 = -7;
/// `gpui_build_tree` finished without an `OP_SET_ROOT` designating a root.
pub const GPUI_STATUS_NO_ROOT: i32 = -8;
/// Two or more nodes in the committed tree carry the same explicit key.
pub const GPUI_STATUS_DUPLICATE_KEY: i32 = -9;

// Rust -> MoonBit callback. MoonBit native does not emit a stable C export
// symbol for an executable build, so we bind directly to the compiled MoonBit
// function's mangled symbol. Rather than hard-code that (fragile) name, the
// `extern` block below is generated by build.rs from `mb_symbol.txt`, which
// `build.sh` fills by extracting the real `app.dispatch` symbol from MoonBit's
// build output — so renames / toolchain mangling changes are tracked
// automatically. The callback is invoked on the main thread, inside the
// (MoonBit-initiated) GPUI event loop — safe under MoonBit's reference-counted
// runtime.
//
// Versioned event envelope (abi_version 3): the four i32 slots carry
//   (abi_version, event_kind, data_a, data_b)
// Slot 0 is always ABI_VERSION so MoonBit can reject a stale Rust binary at
// runtime. Slot 1 selects the event kind. Slots 2–3 are kind-dependent:
//   EVENT_CLICK: data_a = click_id, data_b = 0
//   EVENT_KEY:   data_a = codepoint (single-char key), data_b = modifier bits
//   EVENT_TEXT:  data_a = token (index into EVENT_QUEUE), data_b = byte length
// For EVENT_TEXT the UTF-8 payload lives in a Rust-owned queue; MoonBit copies
// it synchronously via `gpui_event_copy_text` before returning from dispatch.
//
// Generates: `unsafe extern "C" { #[link_name = "_M0FP…3app8dispatch"] fn mb_dispatch(version: i32, kind: i32, data_a: i32, data_b: i32) -> i32; }`
include!(concat!(env!("OUT_DIR"), "/mb_extern.rs"));

/// Rust-owned event payload queue. Text events store their UTF-8 bytes here;
/// the callback passes a token (index) and byte length so MoonBit can copy
/// the payload via `gpui_event_copy_text`. Entries are valid only during the
/// synchronous dispatch call — MoonBit must copy before returning.
static EVENT_QUEUE: Mutex<Vec<Vec<u8>>> = Mutex::new(Vec::new());

/// Copy the text payload for a pending EVENT_TEXT dispatch.
///
/// `token` is the index passed in `data_a`; `buf` must point to at least `len`
/// writable bytes (the `data_b` value). Returns the number of bytes written,
/// or a negative GPUI_STATUS_* on error. The payload is valid only during the
/// dispatch call that provided the token.
#[unsafe(no_mangle)]
pub extern "C" fn gpui_event_copy_text(token: i32, buf: *mut u8, len: i32) -> i32 {
    if token < 0 || buf.is_null() || len < 0 {
        return GPUI_STATUS_INVALID_HANDLE;
    }
    let guard = EVENT_QUEUE.lock().unwrap_or_else(|e| e.into_inner());
    let Some(payload) = guard.get(token as usize) else {
        return GPUI_STATUS_INVALID_HANDLE;
    };
    let copy_len = (len as usize).min(payload.len());
    unsafe {
        std::ptr::copy_nonoverlapping(payload.as_ptr(), buf, copy_len);
    }
    copy_len as i32
}

/// Collect text node contents in DFS pre-order from a committed tree.
fn collect_text_contents(node: &UiNode, out: &mut Vec<u8>) {
    match node {
        UiNode::Div { children, .. } => {
            for child in children {
                collect_text_contents(child, out);
            }
        }
        UiNode::Text { content, .. } => {
            let bytes = content.as_bytes();
            out.extend_from_slice(&(bytes.len() as u32).to_le_bytes());
            out.extend_from_slice(bytes);
        }
    }
}

/// Debug read-back: dump every text node's content from the committed tree for
/// `view` into `buf` as a sequence of `len u32 LE + utf8[len]` records (DFS
/// pre-order). Returns the total number of bytes written, or a negative
/// GPUI_STATUS_* on error. Used by the headless round-trip test (issue #34)
/// to verify MoonBit→C→Rust text fidelity without a GUI.
#[unsafe(no_mangle)]
pub extern "C" fn gpui_debug_dump_text(view: i32, buf: *mut u8, len: i32) -> i32 {
    if view < 0 || buf.is_null() || len < 0 {
        return GPUI_STATUS_INVALID_HANDLE;
    }
    let guard = VIEWS.lock().unwrap_or_else(|e| e.into_inner());
    let Some(Some(root)) = guard.get(view as usize) else {
        return GPUI_STATUS_INVALID_HANDLE;
    };
    let mut payload = Vec::new();
    collect_text_contents(root, &mut payload);
    let copy_len = (len as usize).min(payload.len());
    unsafe {
        std::ptr::copy_nonoverlapping(payload.as_ptr(), buf, copy_len);
    }
    copy_len as i32
}

#[derive(Clone)]
enum UiNode {
    Div {
        width: f32,
        height: f32,
        bg: Option<(u8, u8, u8)>,
        flex: bool,
        flex_col: bool,
        center: bool,
        gap: f32,
        rounded: f32,
        on_click: Option<i32>,
        /// Explicit stable identity, independent of click routing. When set,
        /// `render_node` uses it as the GPUI `ElementId`; duplicate keys within
        /// a committed tree are rejected at `commit_tree`.
        key: Option<String>,
        children: Vec<UiNode>,
    },
    Text {
        content: String,
        color: (u8, u8, u8),
        size: f32,
    },
}


fn report_panic(context: &str, payload: &(dyn Any + Send)) {
    let message = payload
        .downcast_ref::<&str>()
        .copied()
        .or_else(|| payload.downcast_ref::<String>().map(String::as_str))
        .unwrap_or("non-string panic payload");
    eprintln!("gpui-sys: panic in {context}: {message}");
}

fn ffi_export<F>(name: &str, f: F) -> i32
where
    F: FnOnce() -> i32,
{
    match catch_unwind(AssertUnwindSafe(f)) {
        Ok(status) => status,
        Err(payload) => {
            report_panic(name, payload.as_ref());
            GPUI_STATUS_INTERNAL_PANIC
        }
    }
}

fn div_mut(nodes: &mut [Option<UiNode>], handle: i32) -> Result<&mut UiNode, i32> {
    if handle < 0 {
        return Err(GPUI_STATUS_INVALID_HANDLE);
    }
    match nodes.get_mut(handle as usize) {
        None => Err(GPUI_STATUS_INVALID_HANDLE),
        Some(None) => Err(GPUI_STATUS_NODE_ABSENT),
        Some(Some(node @ UiNode::Div { .. })) => Ok(node),
        Some(Some(UiNode::Text { .. })) => Err(GPUI_STATUS_WRONG_NODE_KIND),
    }
}

fn push_node(nodes: &mut Vec<Option<UiNode>>, node: UiNode) -> i32 {
    let Ok(id) = i32::try_from(nodes.len()) else {
        return GPUI_STATUS_INVALID_HANDLE;
    };
    nodes.push(Some(node));
    id
}

// --- Command buffer (issue #5) ---------------------------------------------
//
// MoonBit builds the whole tree as one length-delimited command buffer and
// submits it with a single `gpui_build_tree` call, replacing the former
// property-per-call FFI surface. The buffer is a flat opcode stream: a fixed
// header, then a sequence of `[opcode u8][operands]` records. Node creation
// pushes a handle onto an internal stack; setters apply to the top of the
// stack; `OP_ADD_CHILD` pops child then parent and re-pushes the parent;
// `OP_SET_ROOT` pops the root. All multi-byte integers are little-endian.
//
// Wire layout (little-endian):
//   header:  "GPUI" (4 bytes) | BUFFER_VERSION (u32)
//   OP_DIV            u8
//   OP_TEXT           u8 | len u32 | utf8[len] | r u8 | g u8 | b u8 | size f32
//   OP_SET_SIZE       u8 | w f32 | h f32
//   OP_SET_BG         u8 | r u8 | g u8 | b u8
//   OP_SET_FLEX       u8 | col u8
//   OP_SET_CENTER     u8
//   OP_SET_GAP        u8 | gap f32
//   OP_SET_ROUNDED    u8 | radius f32
//   OP_SET_ON_CLICK   u8 | click_id i32
//   OP_SET_KEY        u8 | len u32 | utf8[len]
//   OP_ADD_CHILD      u8            (pops child, then parent; re-pushes parent)
//   OP_SET_ROOT       u8            (pops the root)
//
// Opcodes and BUFFER_VERSION are generated from abi.toml on both sides, so a
// drift fails the cross-boundary constant check rather than corrupting at
// runtime.

const BUFFER_MAGIC: &[u8; 4] = b"GPUI";

/// A cursor over the command buffer with little-endian readers. Every reader
/// returns `None` on truncation so the parser reports `TRUNCATED_BUFFER`
/// instead of panicking.
struct BufferReader<'a> {
    data: &'a [u8],
    pos: usize,
}

impl<'a> BufferReader<'a> {
    fn new(data: &'a [u8]) -> Self {
        Self { data, pos: 0 }
    }

    fn read_u8(&mut self) -> Option<u8> {
        let byte = *self.data.get(self.pos)?;
        self.pos += 1;
        Some(byte)
    }

    fn read_u32(&mut self) -> Option<u32> {
        let bytes = self.data.get(self.pos..self.pos + 4)?;
        self.pos += 4;
        Some(u32::from_le_bytes([bytes[0], bytes[1], bytes[2], bytes[3]]))
    }

    fn read_i32(&mut self) -> Option<i32> {
        self.read_u32().map(|v| v as i32)
    }

    fn read_f32(&mut self) -> Option<f32> {
        self.read_u32().map(f32::from_bits)
    }

    /// Borrow `len` bytes without copying; advances the cursor.
    fn read_bytes(&mut self, len: usize) -> Option<&'a [u8]> {
        let slice = self.data.get(self.pos..self.pos + len)?;
        self.pos += len;
        Some(slice)
    }

    fn read_string(&mut self) -> Option<String> {
        let len = self.read_u32()? as usize;
        let bytes = self.read_bytes(len)?;
        Some(String::from_utf8_lossy(bytes).into_owned())
    }
}

/// Apply `f` to the div on top of the stack. Fails with `INVALID_HANDLE` if the
/// stack is empty, `NODE_ABSENT` if the top was already moved, `WRONG_NODE_KIND`
/// if the top is a text node.
fn with_top_div<F>(stack: &[i32], nodes: &mut [Option<UiNode>], f: F) -> i32
where
    F: FnOnce(&mut UiNode) -> i32,
{
    let Some(&handle) = stack.last() else {
        return GPUI_STATUS_INVALID_HANDLE;
    };
    match div_mut(nodes, handle) {
        Ok(node) => f(node),
        Err(status) => status,
    }
}

/// Build and commit a tree for `view` from one command buffer. On any failure
/// the staging state is discarded and the previously committed tree is left
/// untouched.
#[unsafe(no_mangle)]
pub extern "C" fn gpui_build_tree(view: i32, ptr: *const u8, len: i32) -> i32 {
    ffi_export("gpui_build_tree", || {
        if view < 0 {
            return GPUI_STATUS_INVALID_HANDLE;
        }
        if ptr.is_null() || len < 0 {
            return GPUI_STATUS_TRUNCATED_BUFFER;
        }
        let data = unsafe { std::slice::from_raw_parts(ptr, len as usize) };
        build_tree_from_buffer(view as usize, data)
    })
}

fn build_tree_from_buffer(view: usize, data: &[u8]) -> i32 {
    let mut reader = BufferReader::new(data);

    // Header: magic + version.
    match reader.read_bytes(BUFFER_MAGIC.len()) {
        Some(m) if m == BUFFER_MAGIC => {}
        _ => return GPUI_STATUS_BAD_BUFFER_VERSION,
    }
    match reader.read_u32() {
        Some(v) if v == BUFFER_VERSION as u32 => {}
        _ => return GPUI_STATUS_BAD_BUFFER_VERSION,
    }

    let mut nodes: Vec<Option<UiNode>> = Vec::new();
    let mut stack: Vec<i32> = Vec::new();
    let mut root: Option<usize> = None;

    loop {
        let Some(opcode) = reader.read_u8() else {
            break; // clean end of buffer
        };
        let status = match opcode as i32 {
            OP_DIV => {
                let id = push_node(
                    &mut nodes,
                    UiNode::Div {
                        width: 0.0,
                        height: 0.0,
                        bg: None,
                        flex: false,
                        flex_col: false,
                        center: false,
                        gap: 0.0,
                        rounded: 0.0,
                        on_click: None,
                        key: None,
                        children: Vec::new(),
                    },
                );
                if id < 0 {
                    id
                } else {
                    stack.push(id);
                    GPUI_STATUS_OK
                }
            }
            OP_TEXT => {
                let (Some(content), Some(r), Some(g), Some(b), Some(size)) = (
                    reader.read_string(),
                    reader.read_u8(),
                    reader.read_u8(),
                    reader.read_u8(),
                    reader.read_f32(),
                ) else {
                    return GPUI_STATUS_TRUNCATED_BUFFER;
                };
                let id = push_node(
                    &mut nodes,
                    UiNode::Text {
                        content,
                        color: (r, g, b),
                        size,
                    },
                );
                if id < 0 {
                    id
                } else {
                    stack.push(id);
                    GPUI_STATUS_OK
                }
            }
            OP_SET_SIZE => {
                let (Some(w), Some(h)) = (reader.read_f32(), reader.read_f32()) else {
                    return GPUI_STATUS_TRUNCATED_BUFFER;
                };
                with_top_div(&stack, &mut nodes, |node| match node {
                    UiNode::Div { width, height, .. } => {
                        *width = w;
                        *height = h;
                        GPUI_STATUS_OK
                    }
                    _ => unreachable!("with_top_div guarantees a div"),
                })
            }
            OP_SET_BG => {
                let (Some(r), Some(g), Some(b)) =
                    (reader.read_u8(), reader.read_u8(), reader.read_u8())
                else {
                    return GPUI_STATUS_TRUNCATED_BUFFER;
                };
                with_top_div(&stack, &mut nodes, |node| match node {
                    UiNode::Div { bg, .. } => {
                        *bg = Some((r, g, b));
                        GPUI_STATUS_OK
                    }
                    _ => unreachable!("with_top_div guarantees a div"),
                })
            }
            OP_SET_FLEX => {
                let Some(col) = reader.read_u8() else {
                    return GPUI_STATUS_TRUNCATED_BUFFER;
                };
                with_top_div(&stack, &mut nodes, |node| match node {
                    UiNode::Div { flex, flex_col, .. } => {
                        *flex = true;
                        *flex_col = col != 0;
                        GPUI_STATUS_OK
                    }
                    _ => unreachable!("with_top_div guarantees a div"),
                })
            }
            OP_SET_CENTER => with_top_div(&stack, &mut nodes, |node| match node {
                UiNode::Div { center, .. } => {
                    *center = true;
                    GPUI_STATUS_OK
                }
                _ => unreachable!("with_top_div guarantees a div"),
            }),
            OP_SET_GAP => {
                let Some(gap) = reader.read_f32() else {
                    return GPUI_STATUS_TRUNCATED_BUFFER;
                };
                with_top_div(&stack, &mut nodes, |node| match node {
                    UiNode::Div { gap: value, .. } => {
                        *value = gap;
                        GPUI_STATUS_OK
                    }
                    _ => unreachable!("with_top_div guarantees a div"),
                })
            }
            OP_SET_ROUNDED => {
                let Some(radius) = reader.read_f32() else {
                    return GPUI_STATUS_TRUNCATED_BUFFER;
                };
                with_top_div(&stack, &mut nodes, |node| match node {
                    UiNode::Div { rounded, .. } => {
                        *rounded = radius;
                        GPUI_STATUS_OK
                    }
                    _ => unreachable!("with_top_div guarantees a div"),
                })
            }
            OP_SET_ON_CLICK => {
                let Some(click_id) = reader.read_i32() else {
                    return GPUI_STATUS_TRUNCATED_BUFFER;
                };
                with_top_div(&stack, &mut nodes, |node| match node {
                    UiNode::Div { on_click, .. } => {
                        *on_click = Some(click_id);
                        GPUI_STATUS_OK
                    }
                    _ => unreachable!("with_top_div guarantees a div"),
                })
            }
            OP_SET_KEY => {
                let Some(key) = reader.read_string() else {
                    return GPUI_STATUS_TRUNCATED_BUFFER;
                };
                with_top_div(&stack, &mut nodes, |node| match node {
                    UiNode::Div { key: slot, .. } => {
                        *slot = Some(key);
                        GPUI_STATUS_OK
                    }
                    _ => unreachable!("with_top_div guarantees a div"),
                })
            }
            OP_ADD_CHILD => {
                let (Some(child), Some(parent)) = (stack.pop(), stack.pop()) else {
                    return GPUI_STATUS_INVALID_HANDLE;
                };
                if parent < 0 || child < 0 || parent == child {
                    return GPUI_STATUS_INVALID_HANDLE;
                }
                let parent_index = parent as usize;
                let child_index = child as usize;
                if parent_index >= nodes.len() || child_index >= nodes.len() {
                    return GPUI_STATUS_INVALID_HANDLE;
                }
                match &nodes[parent_index] {
                    None => return GPUI_STATUS_NODE_ABSENT,
                    Some(UiNode::Text { .. }) => return GPUI_STATUS_WRONG_NODE_KIND,
                    Some(UiNode::Div { .. }) => {}
                }
                if nodes[child_index].is_none() {
                    return GPUI_STATUS_NODE_ABSENT;
                }
                let child_node = nodes[child_index]
                    .take()
                    .expect("child presence was validated");
                let Some(UiNode::Div { children, .. }) = nodes[parent_index].as_mut() else {
                    unreachable!("parent kind was validated");
                };
                children.push(child_node);
                stack.push(parent);
                GPUI_STATUS_OK
            }
            OP_SET_ROOT => {
                let Some(handle) = stack.pop() else {
                    return GPUI_STATUS_INVALID_HANDLE;
                };
                if handle < 0 {
                    return GPUI_STATUS_INVALID_HANDLE;
                }
                match nodes.get(handle as usize) {
                    None => GPUI_STATUS_INVALID_HANDLE,
                    Some(None) => GPUI_STATUS_NODE_ABSENT,
                    Some(Some(_)) => {
                        root = Some(handle as usize);
                        GPUI_STATUS_OK
                    }
                }
            }
            _ => return GPUI_STATUS_UNKNOWN_OPCODE,
        };
        if status != GPUI_STATUS_OK {
            return status;
        }
    }

    // Commit: validate root + duplicate keys, then swap into VIEWS.
    let Some(root_index) = root else {
        return GPUI_STATUS_NO_ROOT;
    };
    if nodes[root_index].is_none() {
        return GPUI_STATUS_NODE_ABSENT;
    }
    {
        let mut seen = std::collections::HashSet::new();
        let root_ref = nodes[root_index].as_ref().expect("root present");
        let mut walk: Vec<&UiNode> = vec![root_ref];
        while let Some(node) = walk.pop() {
            let UiNode::Div { key, children, .. } = node else {
                continue;
            };
            if let Some(key) = key {
                if !seen.insert(key.as_str()) {
                    return GPUI_STATUS_DUPLICATE_KEY;
                }
            }
            walk.extend(children.iter());
        }
    }
    let root_node = nodes[root_index].take().expect("root presence was validated");
    let mut views = VIEWS.lock().unwrap_or_else(|e| e.into_inner());
    if view >= views.len() {
        views.resize(view + 1, None);
    }
    views[view] = Some(root_node);
    GPUI_STATUS_OK
}

#[unsafe(no_mangle)]
pub extern "C" fn gpui_run_window(width: f32, height: f32) -> i32 {
    ffi_export("gpui_run_window", || {
        run_window_with_fallback(width, height)
    })
}

fn run_window(width: f32, height: f32) {
    Application::new().run(move |cx: &mut App| {
        let bounds = Bounds::centered(None, size(px(width), px(height)), cx);
        cx.open_window(
            WindowOptions {
                window_bounds: Some(WindowBounds::Windowed(bounds)),
                ..Default::default()
            },
            |window, cx| {
                cx.new(|cx| {
                    // Focus the view at construction (with `window` available), the
                    // same way GPUI's own examples do — focusing during `render`
                    // does not reliably make the element the OS first responder,
                    // so key events never arrive.
                    let focus = cx.focus_handle();
                    window.focus(&focus);
                    FfiView { focus, view: 0 }
                })
            },
        )
        .unwrap();
        cx.activate(true);
    });
}

fn run_window_with_fallback(width: f32, height: f32) -> i32 {
    match catch_unwind(AssertUnwindSafe(|| run_window(width, height))) {
        Ok(()) => GPUI_STATUS_OK,
        Err(first_panic) => {
            #[cfg(target_os = "linux")]
            if std::env::var_os("WAYLAND_DISPLAY").is_some() {
                report_panic("gpui_run_window (Wayland attempt)", first_panic.as_ref());
                eprintln!(
                    "gpui-sys: Wayland startup failed; unsetting WAYLAND_DISPLAY and retrying with X11"
                );
                // SAFETY: window startup is single-threaded and happens before GPUI
                // creates worker threads that could concurrently read the environment.
                unsafe { std::env::remove_var("WAYLAND_DISPLAY") };
                return match catch_unwind(AssertUnwindSafe(|| run_window(width, height))) {
                    Ok(()) => GPUI_STATUS_OK,
                    Err(second_panic) => {
                        report_panic("gpui_run_window (X11 retry)", second_panic.as_ref());
                        GPUI_STATUS_INTERNAL_PANIC
                    }
                };
            }

            report_panic("gpui_run_window", first_panic.as_ref());
            GPUI_STATUS_INTERNAL_PANIC
        }
    }
}

struct FfiView {
    focus: FocusHandle,
    /// Index into `VIEWS` whose committed tree this view renders.
    view: usize,
}

impl Render for FfiView {
    fn render(&mut self, _window: &mut Window, cx: &mut Context<Self>) -> impl IntoElement {
        // Render the committed root for this view (swapped in by `commit_tree`).
        // Cloned out so the lock is not held while building GPUI elements.
        let root = {
            let guard = VIEWS.lock().unwrap_or_else(|e| e.into_inner());
            guard.get(self.view).cloned().flatten()
        };
        let mut d = div()
            .size_full()
            .flex()
            .flex_col()
            .track_focus(&self.focus)
            .on_key_down(cx.listener(|_this, ev: &KeyDownEvent, _win, cx| {
                let code = key_code(ev);
                let mods = mods_bits(&ev.keystroke.modifiers);
                if code != 0 {
                    let changed =
                        unsafe { mb_dispatch(ABI_VERSION, EVENT_KEY, code, mods) };
                    notify_if_changed(changed, || cx.notify());
                }
                // Emit a text event for keys that produce typed characters
                // (including multi-char keys and IME-composed text). The
                // payload lives in EVENT_QUEUE; MoonBit copies it via
                // gpui_event_copy_text during the synchronous dispatch.
                if let Some(text) = typed_text(ev) {
                    let bytes = text.as_bytes();
                    let token = {
                        let mut q = EVENT_QUEUE.lock().unwrap_or_else(|e| e.into_inner());
                        q.push(bytes.to_vec());
                        (q.len() - 1) as i32
                    };
                    let changed = unsafe {
                        mb_dispatch(ABI_VERSION, EVENT_TEXT, token, bytes.len() as i32)
                    };
                    notify_if_changed(changed, || cx.notify());
                }
            }));
        if let Some(node) = &root {
            if let Some(el) = render_node(node, cx, true) {
                d = d.child(el);
            }
        }
        d
    }
}

/// Codepoint of a single-character key (letters/digits/…); 0 for named or
/// multi-char keys (up/down/enter/…), which this demo ignores. Rust only
/// translates the platform key to a scalar; MoonBit decides what each key does.
fn key_code(ev: &KeyDownEvent) -> i32 {
    let mut chars = ev.keystroke.key.chars();
    match (chars.next(), chars.next()) {
        (Some(c), None) => c as i32,
        _ => 0,
    }
}

/// Typed text for a key event: `key_char` if present (the character that would
/// be inserted, including IME-composed and multi-char keys), else the single
/// `key` character. Returns `None` for pure modifier/navigation keys.
fn typed_text(ev: &KeyDownEvent) -> Option<String> {
    if let Some(s) = &ev.keystroke.key_char {
        if !s.is_empty() {
            return Some(s.clone());
        }
    }
    let k = &ev.keystroke.key;
    if k.chars().count() == 1 && !k.chars().next().unwrap().is_control() {
        Some(k.clone())
    } else {
        None
    }
}

/// Pack modifier flags into the `b` payload slot (bit0 ctrl, 1 alt, 2 shift,
/// 3 platform/cmd, 4 fn). Unused by the demo but kept for completeness.
fn mods_bits(m: &Modifiers) -> i32 {
    (m.control as i32) * MOD_CTRL
        | (m.alt as i32) * MOD_ALT
        | (m.shift as i32) * MOD_SHIFT
        | (m.platform as i32) * MOD_PLATFORM
        | (m.function as i32) * MOD_FUNCTION
}

fn notify_if_changed(changed: i32, notify: impl FnOnce()) {
    if changed == 1 {
        notify();
    }
}

fn render_node(
    node: &UiNode,
    cx: &mut Context<FfiView>,
    fill_available_space: bool,
) -> Option<AnyElement> {
    match node {
        UiNode::Div {
            width,
            height,
            bg,
            flex,
            flex_col,
            center,
            gap,
            rounded,
            on_click,
            key,
            children,
        } => {
            // Build children first (recursion borrows `cx`), then attach the
            // click listener (also borrows `cx`) — kept sequential to avoid an
            // aliasing borrow.
            let mut child_elements: Vec<AnyElement> = Vec::new();
            for child in children {
                if let Some(el) = render_node(child, cx, false) {
                    child_elements.push(el);
                }
            }
            let mut d = div();
            if fill_available_space {
                d = d.size_full();
            }
            if *width > 0.0 && *height > 0.0 {
                d = d.w(px(*width)).h(px(*height));
            }
            if let Some((r, g, b)) = bg {
                d = d.bg(rgb(((*r as u32) << 16) | ((*g as u32) << 8) | (*b as u32)));
            }
            if *flex {
                d = d.flex();
                if *flex_col {
                    d = d.flex_col();
                }
            }
            if *center {
                d = d.justify_center().items_center();
            }
            if *gap > 0.0 {
                d = d.gap(px(*gap));
            }
            if *rounded > 0.0 {
                d = d.rounded(px(*rounded));
            }
            d.extend(child_elements);
            // Element identity: an explicit key (set via `gpui_set_key`) is the
            // stable identity, independent of click routing. Without a key, a
            // clickable div falls back to its click id (the historical scheme).
            // A keyed div gets an id even when not clickable, so stateful
            // elements that only need identity (not click routing) are stable
            // across rebuilds. Duplicate keys are rejected at commit, so ids
            // never collide here.
            match (key.as_deref(), *on_click) {
                (Some(key), on_click) => {
                    let mut d = d.id(SharedString::from(format!("gpui_key:{key}")));
                    if let Some(cid) = on_click {
                        d = d
                            .cursor_pointer()
                            .on_click(cx.listener(move |_this, _ev: &ClickEvent, _win, cx| {
                                let changed = unsafe { mb_dispatch(ABI_VERSION, EVENT_CLICK, cid, 0) };
                                if changed == 1 {
                                    cx.notify();
                                }
                            }));
                    }
                    Some(d.into_any_element())
                }
                (None, Some(cid)) => {
                    // Legacy: identity synthesized from the click id.
                    let el = d
                        .id(("gpui_click", cid as usize))
                        .cursor_pointer()
                        .on_click(cx.listener(move |_this, _ev: &ClickEvent, _win, cx| {
                            let changed = unsafe { mb_dispatch(ABI_VERSION, EVENT_CLICK, cid, 0) };
                            if changed == 1 {
                                cx.notify();
                            }
                        }))
                        .into_any_element();
                    Some(el)
                }
                (None, None) => Some(d.into_any_element()),
            }
        }
        UiNode::Text {
            content,
            color: (r, g, b),
            size,
        } => {
            // GPUI rounds element positions to whole pixels (taffy rounding),
            // so the first glyph of a line always lands at subpixel offset 0 and
            // is rasterized with a hard, un-antialiased left edge — visible as a
            // ~1px "cut" on the left of a leading round glyph such as "G".
            // Interior glyphs land at fractional offsets and get proper
            // antialiasing. Pad the string with a leading (and matching trailing)
            // space so the real first glyph becomes an interior glyph; trailing
            // whitespace is counted in the line width, so centering is preserved.
            let d = div()
                .text_color(rgb(((*r as u32) << 16) | ((*g as u32) << 8) | (*b as u32)))
                .text_size(px(*size))
                .child(format!(" {content} "));
            Some(d.into_any_element())
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    static TEST_MUTEX: Mutex<()> = Mutex::new(());

    fn clear_state() {
        VIEWS.lock().unwrap_or_else(|e| e.into_inner()).clear();
    }

    struct TestReset;

    impl Drop for TestReset {
        fn drop(&mut self) {
            clear_state();
        }
    }

    fn with_test(f: impl FnOnce()) {
        let _lock = TEST_MUTEX.lock().unwrap_or_else(|e| e.into_inner());
        clear_state();
        let _reset = TestReset;
        f();
    }

    /// Inspect the committed view trees.
    fn with_views<F, R>(f: F) -> R
    where
        F: FnOnce(&[Option<UiNode>]) -> R,
    {
        let guard = VIEWS.lock().unwrap_or_else(|e| e.into_inner());
        f(&guard)
    }

    // --- Command buffer builder (mirrors the MoonBit encoder) --------------

    struct Buf(Vec<u8>);

    impl Buf {
        fn new() -> Self {
            let mut b = Buf(Vec::new());
            b.0.extend_from_slice(BUFFER_MAGIC);
            b.u32(BUFFER_VERSION as u32);
            b
        }

        fn u8(&mut self, v: u8) -> &mut Self {
            self.0.push(v);
            self
        }

        fn u32(&mut self, v: u32) -> &mut Self {
            self.0.extend_from_slice(&v.to_le_bytes());
            self
        }

        fn i32(&mut self, v: i32) -> &mut Self {
            self.u32(v as u32)
        }

        fn f32(&mut self, v: f32) -> &mut Self {
            self.u32(v.to_bits())
        }

        fn op(&mut self, opcode: i32) -> &mut Self {
            self.u8(opcode as u8)
        }

        fn str(&mut self, s: &str) -> &mut Self {
            let bytes = s.as_bytes();
            self.u32(bytes.len() as u32);
            self.0.extend_from_slice(bytes);
            self
        }

        fn div(&mut self) -> &mut Self {
            self.op(OP_DIV)
        }

        fn text(&mut self, content: &str, r: u8, g: u8, b: u8, size: f32) -> &mut Self {
            self.op(OP_TEXT).str(content).u8(r).u8(g).u8(b).f32(size)
        }

        fn set_root(&mut self) -> &mut Self {
            self.op(OP_SET_ROOT)
        }

        fn add_child(&mut self) -> &mut Self {
            self.op(OP_ADD_CHILD)
        }

        fn build(&self, view: i32) -> i32 {
            gpui_build_tree(view, self.0.as_ptr(), self.0.len() as i32)
        }
    }

    // --- Happy path --------------------------------------------------------

    #[::core::prelude::v1::test]
    fn builds_and_commits_a_full_tree() {
        with_test(|| {
            let mut b = Buf::new();
            // root: bg(1,2,3), flex col, center, gap 7, rounded 8, key "root"
            b.div()
                .op(OP_SET_BG)
                .u8(1)
                .u8(2)
                .u8(3)
                .op(OP_SET_FLEX)
                .u8(1)
                .op(OP_SET_CENTER)
                .op(OP_SET_GAP)
                .f32(7.0)
                .op(OP_SET_ROUNDED)
                .f32(8.0)
                .op(OP_SET_SIZE)
                .f32(100.0)
                .f32(50.0)
                .op(OP_SET_KEY)
                .str("root");
            // child button: clickable, keyed
            b.div()
                .op(OP_SET_ON_CLICK)
                .i32(9)
                .op(OP_SET_KEY)
                .str("btn");
            b.add_child();
            // text child (non-ASCII + embedded NUL)
            b.text("A\0あ", 4, 5, 6, 14.0);
            b.add_child();
            b.set_root();

            assert_eq!(b.build(0), GPUI_STATUS_OK);
            with_views(|views| {
                let Some(UiNode::Div {
                    width,
                    height,
                    bg: Some((1, 2, 3)),
                    flex: true,
                    flex_col: true,
                    center: true,
                    gap,
                    rounded,
                    on_click: None,
                    key: Some(root_key),
                    children,
                }) = &views[0]
                else {
                    panic!("root div mismatch");
                };
                assert_eq!(*width, 100.0);
                assert_eq!(*height, 50.0);
                assert_eq!(*gap, 7.0);
                assert_eq!(*rounded, 8.0);
                assert_eq!(root_key, "root");
                assert_eq!(children.len(), 2);
                assert!(matches!(
                    &children[0],
                    UiNode::Div {
                        on_click: Some(9),
                        key: Some(k),
                        ..
                    } if k == "btn"
                ));
                assert!(matches!(
                    &children[1],
                    UiNode::Text {
                        content,
                        color: (4, 5, 6),
                        size,
                    } if content == "A\0あ" && *size == 14.0
                ));
            });
        });
    }

    #[::core::prelude::v1::test]
    fn commit_replaces_previous_tree() {
        with_test(|| {
            let mut first = Buf::new();
            first.div().op(OP_SET_BG).u8(1).u8(2).u8(3).set_root();
            assert_eq!(first.build(0), GPUI_STATUS_OK);

            let mut second = Buf::new();
            second.div().op(OP_SET_BG).u8(4).u8(5).u8(6).set_root();
            assert_eq!(second.build(0), GPUI_STATUS_OK);

            with_views(|views| {
                assert!(matches!(
                    &views[0],
                    Some(UiNode::Div { bg: Some((4, 5, 6)), .. })
                ));
            });
        });
    }

    #[::core::prelude::v1::test]
    fn commits_to_distinct_views() {
        with_test(|| {
            let mut v0 = Buf::new();
            v0.div().op(OP_SET_BG).u8(1).u8(0).u8(0).set_root();
            assert_eq!(v0.build(0), GPUI_STATUS_OK);

            let mut v1 = Buf::new();
            v1.div().op(OP_SET_BG).u8(0).u8(1).u8(0).set_root();
            assert_eq!(v1.build(1), GPUI_STATUS_OK);

            with_views(|views| {
                assert!(matches!(&views[0], Some(UiNode::Div { bg: Some((1, 0, 0)), .. })));
                assert!(matches!(&views[1], Some(UiNode::Div { bg: Some((0, 1, 0)), .. })));
            });
        });
    }

    // --- Header / framing validation ---------------------------------------

    #[::core::prelude::v1::test]
    fn rejects_bad_magic_and_version() {
        with_test(|| {
            let mut bad_magic = Buf::new();
            bad_magic.0[0] = b'X';
            bad_magic.div().set_root();
            assert_eq!(bad_magic.build(0), GPUI_STATUS_BAD_BUFFER_VERSION);

            let mut bad_version = Buf::new();
            bad_version.0[4] = 0xFF; // corrupt the version u32
            bad_version.div().set_root();
            assert_eq!(bad_version.build(0), GPUI_STATUS_BAD_BUFFER_VERSION);
        });
    }

    #[::core::prelude::v1::test]
    fn rejects_null_pointer_and_negative_length() {
        with_test(|| {
            assert_eq!(
                gpui_build_tree(0, std::ptr::null(), 8),
                GPUI_STATUS_TRUNCATED_BUFFER
            );
            let b = Buf::new();
            assert_eq!(
                gpui_build_tree(0, b.0.as_ptr(), -1),
                GPUI_STATUS_TRUNCATED_BUFFER
            );
        });
    }

    #[::core::prelude::v1::test]
    fn rejects_truncated_operand() {
        with_test(|| {
            // OP_SET_BG needs 3 bytes; supply only 2 then end the buffer.
            let mut b = Buf::new();
            b.div().op(OP_SET_BG).u8(1).u8(2);
            assert_eq!(b.build(0), GPUI_STATUS_TRUNCATED_BUFFER);

            // OP_TEXT with a declared length longer than the remaining bytes.
            let mut t = Buf::new();
            t.op(OP_TEXT).u32(999).u8(b'a').set_root();
            assert_eq!(t.build(0), GPUI_STATUS_TRUNCATED_BUFFER);
        });
    }

    #[::core::prelude::v1::test]
    fn rejects_huge_string_length_without_panic() {
        with_test(|| {
            // A declared length near the address-space ceiling must report
            // truncation, not overflow the cursor's bounds check.
            let mut t = Buf::new();
            t.op(OP_TEXT).u32(u32::MAX).u8(b'a').set_root();
            assert_eq!(t.build(0), GPUI_STATUS_TRUNCATED_BUFFER);

            let mut k = Buf::new();
            k.div().op(OP_SET_KEY).u32(0x7FFF_FFFF);
            assert_eq!(k.build(0), GPUI_STATUS_TRUNCATED_BUFFER);
        });
    }

    #[::core::prelude::v1::test]
    fn invalid_utf8_text_is_lossy_not_fatal() {
        with_test(|| {
            // The boundary replaces invalid UTF-8 with U+FFFD rather than
            // rejecting: a malformed payload still commits, never panics.
            let mut b = Buf::new();
            b.op(OP_TEXT)
                .u32(2)
                .u8(0xFF)
                .u8(0xFE)
                .u8(1)
                .u8(2)
                .u8(3)
                .f32(10.0)
                .set_root();
            assert_eq!(b.build(0), GPUI_STATUS_OK);
            with_views(|views| {
                assert!(matches!(
                    &views[0],
                    Some(UiNode::Text {
                        content,
                        color: (1, 2, 3),
                        size,
                    }) if content == "\u{FFFD}\u{FFFD}" && *size == 10.0
                ));
            });
        });
    }

    #[::core::prelude::v1::test]
    fn rejects_unknown_opcode() {
        with_test(|| {
            let mut b = Buf::new();
            b.div().u8(0xFE).set_root();
            assert_eq!(b.build(0), GPUI_STATUS_UNKNOWN_OPCODE);
        });
    }

    #[::core::prelude::v1::test]
    fn rejects_negative_view() {
        with_test(|| {
            let b = Buf::new();
            assert_eq!(b.build(-1), GPUI_STATUS_INVALID_HANDLE);
        });
    }

    // --- Stack / handle validation -----------------------------------------

    #[::core::prelude::v1::test]
    fn setter_on_empty_stack_fails() {
        with_test(|| {
            let mut b = Buf::new();
            b.op(OP_SET_CENTER).set_root();
            assert_eq!(b.build(0), GPUI_STATUS_INVALID_HANDLE);
        });
    }

    #[::core::prelude::v1::test]
    fn setter_on_text_top_fails() {
        with_test(|| {
            let mut b = Buf::new();
            b.text("x", 0, 0, 0, 12.0).op(OP_SET_CENTER);
            assert_eq!(b.build(0), GPUI_STATUS_WRONG_NODE_KIND);
        });
    }

    #[::core::prelude::v1::test]
    fn add_child_underflow_fails() {
        with_test(|| {
            // One node on the stack: add_child needs two.
            let mut one = Buf::new();
            one.div().add_child();
            assert_eq!(one.build(0), GPUI_STATUS_INVALID_HANDLE);

            // Empty stack.
            let mut zero = Buf::new();
            zero.add_child();
            assert_eq!(zero.build(0), GPUI_STATUS_INVALID_HANDLE);
        });
    }

    #[::core::prelude::v1::test]
    fn add_child_to_text_parent_fails() {
        with_test(|| {
            let mut b = Buf::new();
            b.text("p", 0, 0, 0, 12.0).div().add_child();
            assert_eq!(b.build(0), GPUI_STATUS_WRONG_NODE_KIND);
        });
    }

    #[::core::prelude::v1::test]
    fn set_root_on_empty_stack_fails() {
        with_test(|| {
            // OP_SET_ROOT with nothing pushed: the stack underflows.
            let mut b = Buf::new();
            b.set_root();
            assert_eq!(b.build(0), GPUI_STATUS_INVALID_HANDLE);
        });
    }

    #[::core::prelude::v1::test]
    fn build_without_root_fails() {
        with_test(|| {
            let mut b = Buf::new();
            b.div(); // created but never set_root
            assert_eq!(b.build(0), GPUI_STATUS_NO_ROOT);
        });
    }

    #[::core::prelude::v1::test]
    fn nested_attachment_commits() {
        with_test(|| {
            // grandparent absorbs parent absorbs child; root = grandparent.
            let mut b = Buf::new();
            b.div(); // grandparent (0)
            b.div(); // parent (1)
            b.div(); // child (2)
            b.add_child(); // parent(1) absorbs child(2); stack [0, 1]
            b.add_child(); // grandparent(0) absorbs parent(1); stack [0]
            b.set_root(); // root = grandparent(0)
            assert_eq!(b.build(0), GPUI_STATUS_OK);
            with_views(|views| {
                assert!(matches!(
                    &views[0],
                    Some(UiNode::Div { children, .. })
                        if matches!(children.as_slice(),
                            [UiNode::Div { children: inner, .. }]
                                if matches!(inner.as_slice(), [UiNode::Div { .. }]))
                ));
            });
        });
    }

    // --- Move / forest semantics (issue #8) --------------------------------

    #[::core::prelude::v1::test]
    fn add_child_moves_not_copies() {
        with_test(|| {
            // Two children attached in order; each appears exactly once under
            // the parent, in attachment order.
            let mut b = Buf::new();
            b.div(); // parent (0)
            b.div().op(OP_SET_BG).u8(1).u8(0).u8(0); // child A (1)
            b.add_child();
            b.div().op(OP_SET_BG).u8(0).u8(1).u8(0); // child B (2)
            b.add_child();
            b.set_root();
            assert_eq!(b.build(0), GPUI_STATUS_OK);
            with_views(|views| {
                assert!(matches!(
                    &views[0],
                    Some(UiNode::Div { children, .. })
                        if matches!(
                            children.as_slice(),
                            [
                                UiNode::Div {
                                    bg: Some((1, 0, 0)),
                                    children: a,
                                    ..
                                },
                                UiNode::Div {
                                    bg: Some((0, 1, 0)),
                                    children: c,
                                    ..
                                },
                            ] if a.is_empty() && c.is_empty()
                        )
                ));
            });
        });
    }

    #[::core::prelude::v1::test]
    fn subtree_moves_intact() {
        with_test(|| {
            // Grandchild attached to child, then child moved into root: the
            // whole subtree relocates with its contents, nothing duplicated.
            let mut b = Buf::new();
            b.div(); // root (0)
            b.div(); // child (1)
            b.div().op(OP_SET_BG).u8(7).u8(7).u8(7); // grandchild (2)
            b.add_child(); // 2 into 1
            b.add_child(); // 1 into 0
            b.set_root();
            assert_eq!(b.build(0), GPUI_STATUS_OK);
            with_views(|views| {
                assert!(matches!(
                    &views[0],
                    Some(UiNode::Div { children: root_kids, .. })
                        if matches!(
                            root_kids.as_slice(),
                            [UiNode::Div { children: inner, .. }]
                                if matches!(
                                    inner.as_slice(),
                                    [UiNode::Div {
                                        bg: Some((7, 7, 7)),
                                        children: leaf,
                                        ..
                                    }] if leaf.is_empty()
                                )
                        )
                ));
            });
        });
    }

    #[::core::prelude::v1::test]
    fn unattached_nodes_are_dropped_from_commit() {
        with_test(|| {
            // Forest model: only the designated root is committed; a node
            // never attached nor rooted (here handle 0) is silently discarded.
            let mut b = Buf::new();
            b.div().op(OP_SET_BG).u8(9).u8(9).u8(9); // orphan (0)
            b.div().op(OP_SET_BG).u8(1).u8(2).u8(3); // root (1)
            b.set_root(); // pops 1
            assert_eq!(b.build(0), GPUI_STATUS_OK);
            with_views(|views| {
                assert!(matches!(
                    &views[0],
                    Some(UiNode::Div {
                        bg: Some((1, 2, 3)),
                        children,
                        ..
                    }) if children.is_empty()
                ));
            });
        });
    }

    #[::core::prelude::v1::test]
    fn last_set_root_wins() {
        with_test(|| {
            // Two OP_SET_ROOT in one buffer: the last designation commits.
            let mut b = Buf::new();
            b.div().op(OP_SET_BG).u8(1).u8(0).u8(0);
            b.set_root();
            b.div().op(OP_SET_BG).u8(0).u8(1).u8(0);
            b.set_root();
            assert_eq!(b.build(0), GPUI_STATUS_OK);
            with_views(|views| {
                assert!(matches!(
                    &views[0],
                    Some(UiNode::Div { bg: Some((0, 1, 0)), .. })
                ));
            });
        });
    }

    // --- Key semantics (issue #9, now via the buffer) ----------------------

    #[::core::prelude::v1::test]
    fn commit_rejects_duplicate_keys_in_tree() {
        with_test(|| {
            let mut b = Buf::new();
            b.div(); // root
            b.div().op(OP_SET_KEY).str("same");
            b.add_child();
            b.div().op(OP_SET_KEY).str("same");
            b.add_child();
            b.set_root();
            assert_eq!(b.build(0), GPUI_STATUS_DUPLICATE_KEY);
            // Failed build leaves the previous (empty) committed tree untouched.
            with_views(|views| assert!(views.is_empty() || views[0].is_none()));
        });
    }

    #[::core::prelude::v1::test]
    fn commit_allows_distinct_keys() {
        with_test(|| {
            let mut b = Buf::new();
            b.div();
            b.div().op(OP_SET_KEY).str("a");
            b.add_child();
            b.div().op(OP_SET_KEY).str("b");
            b.add_child();
            b.set_root();
            assert_eq!(b.build(0), GPUI_STATUS_OK);
        });
    }

    #[::core::prelude::v1::test]
    fn commit_allows_duplicate_click_ids() {
        with_test(|| {
            // click_id is action routing, not identity: duplicates are allowed.
            let mut b = Buf::new();
            b.div();
            b.div().op(OP_SET_ON_CLICK).i32(7);
            b.add_child();
            b.div().op(OP_SET_ON_CLICK).i32(7);
            b.add_child();
            b.set_root();
            assert_eq!(b.build(0), GPUI_STATUS_OK);
        });
    }

    // --- Notification gate -------------------------------------------------

    #[::core::prelude::v1::test]
    fn notification_gate_accepts_only_changed_one() {
        let calls = std::cell::Cell::new(0);
        notify_if_changed(0, || calls.set(calls.get() + 1));
        notify_if_changed(-1, || calls.set(calls.get() + 1));
        notify_if_changed(2, || calls.set(calls.get() + 1));
        assert_eq!(calls.get(), 0);
        notify_if_changed(1, || calls.set(calls.get() + 1));
        assert_eq!(calls.get(), 1);
    }

    // --- Cross-boundary ABI drift guard ------------------------------------

    /// Cross-boundary drift guard (issue #8: EVENT_*/EV_* compatibility).
    ///
    /// The integers Rust ships as the callback `kind` and modifier bits must be
    /// the exact integers MoonBit decodes. Both sides are generated from
    /// `gpui-sys/abi.toml`, but generation is independent (build.rs for Rust,
    /// build.sh/awk for MoonBit) and only *warns* on drift — nothing fails. This
    /// pins the contract headlessly: every compiled Rust constant must equal
    /// `abi.toml`, and `abi.toml` must equal the generated MoonBit file, so a
    /// stale or hand-edited generated file on either side fails here rather than
    /// at runtime.
    #[::core::prelude::v1::test]
    fn abi_constants_match_across_boundary() {
        let manifest = std::env::var("CARGO_MANIFEST_DIR").unwrap();
        let root = std::path::Path::new(&manifest);

        // abi.toml is the single source of truth: [section] headers + key = int.
        let abi_toml = std::fs::read_to_string(root.join("abi.toml")).expect("read abi.toml");
        let mut expected: std::collections::BTreeMap<String, i32> =
            std::collections::BTreeMap::new();
        let mut in_callback = false;
        for raw in abi_toml.lines() {
            let line = raw.split('#').next().unwrap().trim();
            if line.is_empty() {
                continue;
            }
            if let Some(name) = line.strip_prefix('[').and_then(|s| s.strip_suffix(']')) {
                in_callback = name.trim() == "callback";
                continue;
            }
            if in_callback {
                continue; // callback signature is string-valued, not a numeric constant
            }
            let (key, value) = line.split_once('=').expect("abi.toml key = value");
            let key = key.trim();
            let Ok(value) = value.trim().parse::<i32>() else {
                continue; // skip non-integer values defensively
            };
            let key = if key == "abi_version" { "ABI_VERSION" } else { key };
            expected.insert(key.to_string(), value);
        }
        assert!(
            !expected.is_empty(),
            "abi.toml yielded no numeric constants; parser drift?"
        );

        // 1) Compiled Rust constants must equal the source of truth.
        let rust_constants = [
            ("ABI_VERSION", ABI_VERSION),
            ("EVENT_CLICK", EVENT_CLICK),
            ("EVENT_KEY", EVENT_KEY),
            ("EVENT_TEXT", EVENT_TEXT),
            ("MOD_CTRL", MOD_CTRL),
            ("MOD_ALT", MOD_ALT),
            ("MOD_SHIFT", MOD_SHIFT),
            ("MOD_PLATFORM", MOD_PLATFORM),
            ("MOD_FUNCTION", MOD_FUNCTION),
            ("OP_DIV", OP_DIV),
            ("OP_TEXT", OP_TEXT),
            ("OP_SET_SIZE", OP_SET_SIZE),
            ("OP_SET_BG", OP_SET_BG),
            ("OP_SET_FLEX", OP_SET_FLEX),
            ("OP_SET_CENTER", OP_SET_CENTER),
            ("OP_SET_GAP", OP_SET_GAP),
            ("OP_SET_ROUNDED", OP_SET_ROUNDED),
            ("OP_SET_ON_CLICK", OP_SET_ON_CLICK),
            ("OP_SET_KEY", OP_SET_KEY),
            ("OP_ADD_CHILD", OP_ADD_CHILD),
            ("OP_SET_ROOT", OP_SET_ROOT),
            ("BUFFER_VERSION", BUFFER_VERSION),
        ];
        for (name, compiled) in rust_constants {
            assert_eq!(
                expected.get(name).copied(),
                Some(compiled),
                "Rust {name} drifted from abi.toml (regenerate src/abi_constants.rs via build.rs)"
            );
        }
        for name in expected.keys() {
            assert!(
                rust_constants.iter().any(|(n, _)| n == name),
                "abi.toml constant {name} has no compiled Rust counterpart"
            );
        }

        // 2) The generated MoonBit file must carry the same values. Whitespace is
        //    stripped so the check survives `moon fmt` spacing changes.
        let mb = std::fs::read_to_string(root.join("../moonbit-bindings/abi_constants.mbt"))
            .expect("read moonbit-bindings/abi_constants.mbt (run build.sh to regenerate)");
        let mb_compact: String = mb.chars().filter(|c| !c.is_whitespace()).collect();
        for (name, value) in &expected {
            let needle = format!("pubconst{name}:Int={value}");
            assert!(
                mb_compact.contains(&needle),
                "MoonBit abi_constants.mbt missing `pub const {name} : Int = {value}` — regenerate via build.sh"
            );
        }
    }

    #[::core::prelude::v1::test]
    fn debug_dump_text_round_trips() {
        with_test(|| {
            // div { text("A\0あ"), text("🎉") }
            let mut b = Buf::new();
            b.div()
                .text("A\0あ", 255, 255, 255, 16.0)
                .add_child()
                .text("🎉", 255, 255, 255, 16.0)
                .add_child()
                .set_root();
            assert_eq!(b.build(0), GPUI_STATUS_OK);

            // Expected: len u32 LE + utf8 for each text node, DFS pre-order.
            let mut expected = Vec::new();
            for s in ["A\0あ", "🎉"] {
                let bytes = s.as_bytes();
                expected.extend_from_slice(&(bytes.len() as u32).to_le_bytes());
                expected.extend_from_slice(bytes);
            }

            let mut buf = vec![0u8; 256];
            let n = gpui_debug_dump_text(0, buf.as_mut_ptr(), buf.len() as i32);
            assert_eq!(n, expected.len() as i32);
            assert_eq!(&buf[..n as usize], &expected[..]);
        });
    }

    #[::core::prelude::v1::test]
    fn debug_dump_text_rejects_bad_args() {
        with_test(|| {
            let mut buf = [0u8; 8];
            assert_eq!(
                gpui_debug_dump_text(-1, buf.as_mut_ptr(), 8),
                GPUI_STATUS_INVALID_HANDLE
            );
            assert_eq!(
                gpui_debug_dump_text(0, std::ptr::null_mut(), 8),
                GPUI_STATUS_INVALID_HANDLE
            );
            assert_eq!(
                gpui_debug_dump_text(0, buf.as_mut_ptr(), -1),
                GPUI_STATUS_INVALID_HANDLE
            );
            // No tree committed yet.
            assert_eq!(
                gpui_debug_dump_text(0, buf.as_mut_ptr(), 8),
                GPUI_STATUS_INVALID_HANDLE
            );
        });
    }
}
