use gpui::*;
use std::any::Any;
use std::panic::{AssertUnwindSafe, catch_unwind};
use std::sync::Mutex;

mod abi_constants;
use abi_constants::{
    ABI_VERSION, EVENT_CLICK, EVENT_KEY, MOD_ALT, MOD_CTRL, MOD_FUNCTION, MOD_PLATFORM, MOD_SHIFT,
};

// Reference the version as a build-time sanity anchor until runtime FFI negotiation exists.
const _: () = assert!(ABI_VERSION > 0);

static NODES: Mutex<Vec<Option<UiNode>>> = Mutex::new(Vec::new());

/// Operation completed successfully.
pub const GPUI_STATUS_OK: i32 = 0;
/// A handle was negative, out of range, duplicated, or could not be allocated.
pub const GPUI_STATUS_INVALID_HANDLE: i32 = -1;
/// The handle refers to the wrong kind of node for the requested operation.
pub const GPUI_STATUS_WRONG_NODE_KIND: i32 = -2;
/// The node was already moved into another node by `gpui_add_child`.
pub const GPUI_STATUS_NODE_ABSENT: i32 = -3;
/// An internal panic was caught before it could cross the C boundary.
pub const GPUI_STATUS_INTERNAL_PANIC: i32 = -4;

// Rust -> MoonBit callback. MoonBit native does not emit a stable C export
// symbol for an executable build, so we bind directly to the compiled MoonBit
// function's mangled symbol. Rather than hard-code that (fragile) name, the
// `extern` block below is generated by build.rs from `mb_symbol.txt`, which
// `build.sh` fills by extracting the real `app.dispatch` symbol from MoonBit's
// build output — so renames / toolchain mangling changes are tracked
// automatically. The callback is invoked on click, on the main thread, while we
// are already inside the (MoonBit-initiated) GPUI event loop — safe under
// MoonBit's reference-counted runtime.
//
// Generates: `unsafe extern "C" { #[link_name = "_M0FP…3app8dispatch"] fn mb_dispatch(kind: i32, id: i32, a: i32, b: i32); }`
include!(concat!(env!("OUT_DIR"), "/mb_extern.rs"));

#[derive(Clone)]
enum UiNode {
    Div {
        width: f32,
        height: f32,
        bg: Option<(u8, u8, u8)>,
        flex: bool,
        flex_col: bool,
        center: bool,
        gap: f32,
        rounded: f32,
        on_click: Option<i32>,
        children: Vec<UiNode>,
    },
    Text {
        content: String,
        color: (u8, u8, u8),
        size: f32,
    },
}

fn with_nodes<F, R>(f: F) -> R
where
    F: FnOnce(&mut Vec<Option<UiNode>>) -> R,
{
    f(&mut NODES.lock().unwrap_or_else(|e| e.into_inner()))
}

fn report_panic(context: &str, payload: &(dyn Any + Send)) {
    let message = payload
        .downcast_ref::<&str>()
        .copied()
        .or_else(|| payload.downcast_ref::<String>().map(String::as_str))
        .unwrap_or("non-string panic payload");
    eprintln!("gpui-sys: panic in {context}: {message}");
}

fn ffi_export<F>(name: &str, f: F) -> i32
where
    F: FnOnce() -> i32,
{
    match catch_unwind(AssertUnwindSafe(f)) {
        Ok(status) => status,
        Err(payload) => {
            report_panic(name, payload.as_ref());
            GPUI_STATUS_INTERNAL_PANIC
        }
    }
}

fn div_mut(nodes: &mut [Option<UiNode>], handle: i32) -> Result<&mut UiNode, i32> {
    if handle < 0 {
        return Err(GPUI_STATUS_INVALID_HANDLE);
    }
    match nodes.get_mut(handle as usize) {
        None => Err(GPUI_STATUS_INVALID_HANDLE),
        Some(None) => Err(GPUI_STATUS_NODE_ABSENT),
        Some(Some(node @ UiNode::Div { .. })) => Ok(node),
        Some(Some(UiNode::Text { .. })) => Err(GPUI_STATUS_WRONG_NODE_KIND),
    }
}

fn push_node(nodes: &mut Vec<Option<UiNode>>, node: UiNode) -> i32 {
    let Ok(id) = i32::try_from(nodes.len()) else {
        return GPUI_STATUS_INVALID_HANDLE;
    };
    nodes.push(Some(node));
    id
}

#[unsafe(no_mangle)]
pub extern "C" fn gpui_create_div() -> i32 {
    ffi_export("gpui_create_div", || {
        with_nodes(|nodes| {
            push_node(
                nodes,
                UiNode::Div {
                    width: 0.0,
                    height: 0.0,
                    bg: None,
                    flex: false,
                    flex_col: false,
                    center: false,
                    gap: 0.0,
                    rounded: 0.0,
                    on_click: None,
                    children: Vec::new(),
                },
            )
        })
    })
}

/// Mark a div as clickable. `click_id` is passed back to MoonBit's `dispatch`
/// when the div is clicked.
#[unsafe(no_mangle)]
pub extern "C" fn gpui_set_on_click(handle: i32, click_id: i32) -> i32 {
    ffi_export("gpui_set_on_click", || {
        with_nodes(|nodes| match div_mut(nodes, handle) {
            Ok(UiNode::Div { on_click, .. }) => {
                *on_click = Some(click_id);
                GPUI_STATUS_OK
            }
            Ok(_) => unreachable!(),
            Err(status) => status,
        })
    })
}

/// Clear the whole node tree so MoonBit can rebuild it from scratch (used on
/// re-render after a click).
#[unsafe(no_mangle)]
pub extern "C" fn gpui_reset() -> i32 {
    ffi_export("gpui_reset", || {
        with_nodes(|nodes| nodes.clear());
        GPUI_STATUS_OK
    })
}

#[unsafe(no_mangle)]
pub extern "C" fn gpui_set_size(handle: i32, w: f32, h: f32) -> i32 {
    ffi_export("gpui_set_size", || {
        with_nodes(|nodes| match div_mut(nodes, handle) {
            Ok(UiNode::Div { width, height, .. }) => {
                *width = w;
                *height = h;
                GPUI_STATUS_OK
            }
            Ok(_) => unreachable!(),
            Err(status) => status,
        })
    })
}

#[unsafe(no_mangle)]
pub extern "C" fn gpui_set_bg(handle: i32, r: u8, g: u8, b: u8) -> i32 {
    ffi_export("gpui_set_bg", || {
        with_nodes(|nodes| match div_mut(nodes, handle) {
            Ok(UiNode::Div { bg, .. }) => {
                *bg = Some((r, g, b));
                GPUI_STATUS_OK
            }
            Ok(_) => unreachable!(),
            Err(status) => status,
        })
    })
}

#[unsafe(no_mangle)]
pub extern "C" fn gpui_set_flex(handle: i32, col: i32) -> i32 {
    ffi_export("gpui_set_flex", || {
        with_nodes(|nodes| match div_mut(nodes, handle) {
            Ok(UiNode::Div { flex, flex_col, .. }) => {
                *flex = true;
                *flex_col = col != 0;
                GPUI_STATUS_OK
            }
            Ok(_) => unreachable!(),
            Err(status) => status,
        })
    })
}

#[unsafe(no_mangle)]
pub extern "C" fn gpui_set_center(handle: i32) -> i32 {
    ffi_export("gpui_set_center", || {
        with_nodes(|nodes| match div_mut(nodes, handle) {
            Ok(UiNode::Div { center, .. }) => {
                *center = true;
                GPUI_STATUS_OK
            }
            Ok(_) => unreachable!(),
            Err(status) => status,
        })
    })
}

#[unsafe(no_mangle)]
pub extern "C" fn gpui_set_gap(handle: i32, gap: f32) -> i32 {
    ffi_export("gpui_set_gap", || {
        with_nodes(|nodes| match div_mut(nodes, handle) {
            Ok(UiNode::Div { gap: value, .. }) => {
                *value = gap;
                GPUI_STATUS_OK
            }
            Ok(_) => unreachable!(),
            Err(status) => status,
        })
    })
}

#[unsafe(no_mangle)]
pub extern "C" fn gpui_set_rounded(handle: i32, radius: f32) -> i32 {
    ffi_export("gpui_set_rounded", || {
        with_nodes(|nodes| match div_mut(nodes, handle) {
            Ok(UiNode::Div { rounded, .. }) => {
                *rounded = radius;
                GPUI_STATUS_OK
            }
            Ok(_) => unreachable!(),
            Err(status) => status,
        })
    })
}

#[unsafe(no_mangle)]
pub extern "C" fn gpui_create_text(
    ptr: *const u8,
    len: i32,
    r: u8,
    g: u8,
    b: u8,
    size: f32,
) -> i32 {
    ffi_export("gpui_create_text", || {
        let content = if ptr.is_null() || len <= 0 {
            String::new()
        } else {
            String::from_utf8_lossy(unsafe { std::slice::from_raw_parts(ptr, len as usize) })
                .into_owned()
        };
        with_nodes(|nodes| {
            push_node(
                nodes,
                UiNode::Text {
                    content,
                    color: (r, g, b),
                    size,
                },
            )
        })
    })
}

#[unsafe(no_mangle)]
pub extern "C" fn gpui_add_child(parent: i32, child: i32) -> i32 {
    ffi_export("gpui_add_child", || {
        with_nodes(|nodes| {
            if parent < 0 || child < 0 || parent == child {
                return GPUI_STATUS_INVALID_HANDLE;
            }
            let parent_index = parent as usize;
            let child_index = child as usize;
            if parent_index >= nodes.len() || child_index >= nodes.len() {
                return GPUI_STATUS_INVALID_HANDLE;
            }
            match &nodes[parent_index] {
                None => return GPUI_STATUS_NODE_ABSENT,
                Some(UiNode::Text { .. }) => return GPUI_STATUS_WRONG_NODE_KIND,
                Some(UiNode::Div { .. }) => {}
            }
            if nodes[child_index].is_none() {
                return GPUI_STATUS_NODE_ABSENT;
            }

            let child_node = nodes[child_index]
                .take()
                .expect("child presence was validated");
            let Some(UiNode::Div { children, .. }) = nodes[parent_index].as_mut() else {
                unreachable!("parent kind was validated");
            };
            children.push(child_node);
            GPUI_STATUS_OK
        })
    })
}

#[unsafe(no_mangle)]
pub extern "C" fn gpui_run_window(width: f32, height: f32) -> i32 {
    ffi_export("gpui_run_window", || {
        run_window_with_fallback(width, height)
    })
}

fn run_window(width: f32, height: f32) {
    Application::new().run(move |cx: &mut App| {
        let bounds = Bounds::centered(None, size(px(width), px(height)), cx);
        cx.open_window(
            WindowOptions {
                window_bounds: Some(WindowBounds::Windowed(bounds)),
                ..Default::default()
            },
            |window, cx| {
                cx.new(|cx| {
                    // Focus the view at construction (with `window` available), the
                    // same way GPUI's own examples do — focusing during `render`
                    // does not reliably make the element the OS first responder,
                    // so key events never arrive.
                    let focus = cx.focus_handle();
                    window.focus(&focus);
                    FfiView { focus }
                })
            },
        )
        .unwrap();
        cx.activate(true);
    });
}

fn run_window_with_fallback(width: f32, height: f32) -> i32 {
    match catch_unwind(AssertUnwindSafe(|| run_window(width, height))) {
        Ok(()) => GPUI_STATUS_OK,
        Err(first_panic) => {
            #[cfg(target_os = "linux")]
            if std::env::var_os("WAYLAND_DISPLAY").is_some() {
                report_panic("gpui_run_window (Wayland attempt)", first_panic.as_ref());
                eprintln!(
                    "gpui-sys: Wayland startup failed; unsetting WAYLAND_DISPLAY and retrying with X11"
                );
                // SAFETY: window startup is single-threaded and happens before GPUI
                // creates worker threads that could concurrently read the environment.
                unsafe { std::env::remove_var("WAYLAND_DISPLAY") };
                return match catch_unwind(AssertUnwindSafe(|| run_window(width, height))) {
                    Ok(()) => GPUI_STATUS_OK,
                    Err(second_panic) => {
                        report_panic("gpui_run_window (X11 retry)", second_panic.as_ref());
                        GPUI_STATUS_INTERNAL_PANIC
                    }
                };
            }

            report_panic("gpui_run_window", first_panic.as_ref());
            GPUI_STATUS_INTERNAL_PANIC
        }
    }
}

struct FfiView {
    focus: FocusHandle,
}

impl Render for FfiView {
    fn render(&mut self, _window: &mut Window, cx: &mut Context<Self>) -> impl IntoElement {
        let nodes = {
            let guard = NODES.lock().unwrap_or_else(|e| e.into_inner());
            guard.iter().flatten().cloned().collect::<Vec<_>>()
        };
        let mut children = Vec::new();
        for node in &nodes {
            if let Some(el) = render_node(node, cx, true) {
                children.push(el);
            }
        }
        let mut d = div()
            .size_full()
            .flex()
            .flex_col()
            .track_focus(&self.focus)
            .on_key_down(cx.listener(|_this, ev: &KeyDownEvent, _win, cx| {
                let code = key_code(ev);
                if code != 0 {
                    let mods = mods_bits(&ev.keystroke.modifiers);
                    unsafe { mb_dispatch(EVENT_KEY, 0, code, mods) };
                    cx.notify();
                }
            }));
        d.extend(children);
        d
    }
}

/// Codepoint of a single-character key (letters/digits/…); 0 for named or
/// multi-char keys (up/down/enter/…), which this demo ignores. Rust only
/// translates the platform key to a scalar; MoonBit decides what each key does.
fn key_code(ev: &KeyDownEvent) -> i32 {
    let mut chars = ev.keystroke.key.chars();
    match (chars.next(), chars.next()) {
        (Some(c), None) => c as i32,
        _ => 0,
    }
}

/// Pack modifier flags into the `b` payload slot (bit0 ctrl, 1 alt, 2 shift,
/// 3 platform/cmd, 4 fn). Unused by the demo but kept for completeness.
fn mods_bits(m: &Modifiers) -> i32 {
    (m.control as i32) * MOD_CTRL
        | (m.alt as i32) * MOD_ALT
        | (m.shift as i32) * MOD_SHIFT
        | (m.platform as i32) * MOD_PLATFORM
        | (m.function as i32) * MOD_FUNCTION
}

fn render_node(
    node: &UiNode,
    cx: &mut Context<FfiView>,
    fill_available_space: bool,
) -> Option<AnyElement> {
    match node {
        UiNode::Div {
            width,
            height,
            bg,
            flex,
            flex_col,
            center,
            gap,
            rounded,
            on_click,
            children,
        } => {
            // Build children first (recursion borrows `cx`), then attach the
            // click listener (also borrows `cx`) — kept sequential to avoid an
            // aliasing borrow.
            let mut child_elements: Vec<AnyElement> = Vec::new();
            for child in children {
                if let Some(el) = render_node(child, cx, false) {
                    child_elements.push(el);
                }
            }
            let mut d = div();
            if fill_available_space {
                d = d.size_full();
            }
            if *width > 0.0 && *height > 0.0 {
                d = d.w(px(*width)).h(px(*height));
            }
            if let Some((r, g, b)) = bg {
                d = d.bg(rgb(
                    ((*r as u32) << 16) | ((*g as u32) << 8) | (*b as u32)
                ));
            }
            if *flex {
                d = d.flex();
                if *flex_col {
                    d = d.flex_col();
                }
            }
            if *center {
                d = d.justify_center().items_center();
            }
            if *gap > 0.0 {
                d = d.gap(px(*gap));
            }
            if *rounded > 0.0 {
                d = d.rounded(px(*rounded));
            }
            d.extend(child_elements);
            if let Some(cid) = *on_click {
                // A stable ElementId derived from the click id (not the volatile
                // node handle) keeps GPUI's stateful-element identity across
                // rebuilds. On click, hand the id back to MoonBit and re-render.
                let el = d
                    .id(("gpui_click", cid as usize))
                    .cursor_pointer()
                    .on_click(cx.listener(move |_this, _ev: &ClickEvent, _win, cx| {
                        unsafe { mb_dispatch(EVENT_CLICK, cid, 0, 0) };
                        cx.notify();
                    }))
                    .into_any_element();
                Some(el)
            } else {
                Some(d.into_any_element())
            }
        }
        UiNode::Text {
            content,
            color: (r, g, b),
            size,
        } => {
            // GPUI rounds element positions to whole pixels (taffy rounding),
            // so the first glyph of a line always lands at subpixel offset 0 and
            // is rasterized with a hard, un-antialiased left edge — visible as a
            // ~1px "cut" on the left of a leading round glyph such as "G".
            // Interior glyphs land at fractional offsets and get proper
            // antialiasing. Pad the string with a leading (and matching trailing)
            // space so the real first glyph becomes an interior glyph; trailing
            // whitespace is counted in the line width, so centering is preserved.
            let d = div()
                .text_color(rgb(
                    ((*r as u32) << 16) | ((*g as u32) << 8) | (*b as u32)
                ))
                .text_size(px(*size))
                .child(format!(" {content} "));
            Some(d.into_any_element())
        }
    }
}
