#ifndef GPUI_SYS_H
#define GPUI_SYS_H

/* Warning: this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Operation completed successfully.
 */
#define gpui_GPUI_STATUS_OK 0

/**
 * A handle was negative, out of range, duplicated, or could not be allocated.
 */
#define gpui_GPUI_STATUS_INVALID_HANDLE -1

/**
 * The handle refers to the wrong kind of node for the requested operation.
 */
#define gpui_GPUI_STATUS_WRONG_NODE_KIND -2

/**
 * The node was already moved into another node by `gpui_add_child`.
 */
#define gpui_GPUI_STATUS_NODE_ABSENT -3

/**
 * An internal panic was caught before it could cross the C boundary.
 */
#define gpui_GPUI_STATUS_INTERNAL_PANIC -4

/**
 * The command buffer header magic or version did not match.
 */
#define gpui_GPUI_STATUS_BAD_BUFFER_VERSION -5

/**
 * The command buffer ended mid-field, or carried a truncated/oversized payload.
 */
#define gpui_GPUI_STATUS_TRUNCATED_BUFFER -6

/**
 * The command buffer named an opcode this build does not recognize.
 */
#define gpui_GPUI_STATUS_UNKNOWN_OPCODE -7

/**
 * `gpui_build_tree` finished without an `OP_SET_ROOT` designating a root.
 */
#define gpui_GPUI_STATUS_NO_ROOT -8

/**
 * Two or more nodes in the committed tree carry the same explicit key.
 */
#define gpui_GPUI_STATUS_DUPLICATE_KEY -9

/**
 * Copy the text payload for a pending EVENT_TEXT dispatch.
 *
 * `token` is the index passed in `data_a`; `buf` must point to at least `len`
 * writable bytes (the `data_b` value). Returns the number of bytes written,
 * or a negative GPUI_STATUS_* on error. The payload is valid only during the
 * dispatch call that provided the token.
 */
int32_t gpui_event_copy_text(int32_t token, uint8_t *buf, int32_t len);

/**
 * Debug read-back: dump every text node's content from the committed tree for
 * `view` into `buf` as a sequence of `len u32 LE + utf8[len]` records (DFS
 * pre-order). Returns the total number of bytes written, or a negative
 * GPUI_STATUS_* on error. Used by the headless round-trip test (issue #34)
 * to verify MoonBit→C→Rust text fidelity without a GUI.
 */
int32_t gpui_debug_dump_text(int32_t view, uint8_t *buf, int32_t len);

/**
 * Build and commit a tree for `view` from one command buffer. On any failure
 * the staging state is discarded and the previously committed tree is left
 * untouched.
 */
int32_t gpui_build_tree(int32_t view, const uint8_t *ptr, int32_t len);

/**
 * Open a window rendering the committed tree for `view` (index into
 * `VIEWS`) and block in the GPUI event loop. A negative `view` fails with
 * `GPUI_STATUS_INVALID_HANDLE` before any GPUI startup.
 */
int32_t gpui_run_window(int32_t view, float width, float height);

#endif  /* GPUI_SYS_H */
