#ifndef GPUI_SYS_H
#define GPUI_SYS_H

/* Warning: this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

int32_t gpui_create_div(void);

/**
 * Mark a div as clickable. `click_id` is passed back to MoonBit's `dispatch`
 * when the div is clicked.
 */
void gpui_set_on_click(int32_t handle, int32_t click_id);

/**
 * Clear the whole node tree so MoonBit can rebuild it from scratch (used on
 * re-render after a click).
 */
void gpui_reset(void);

void gpui_set_size(int32_t handle, float w, float h);

void gpui_set_bg(int32_t handle, uint8_t r, uint8_t g, uint8_t b);

void gpui_set_flex(int32_t handle, int32_t col);

void gpui_set_center(int32_t handle);

void gpui_set_gap(int32_t handle, float gap);

void gpui_set_rounded(int32_t handle, float radius);

int32_t gpui_create_text(const char *text, uint8_t r, uint8_t g, uint8_t b, float size);

void gpui_add_child(int32_t parent, int32_t child);

void gpui_run_window(float width, float height);

#endif  /* GPUI_SYS_H */
